<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="model">
      <node TEXT="If  these two features are very similar  the Pearson criterion will be close to  one  while if these two features are very dissimilar  the Pearson criterion  will be close to zero. Furthermore  in our developed feature selection method  as opposed  to previous models  84 86  where only feature relevance is employed to  select final features  a subset of features with high importance and rel  evancy will be chosen. These capabilities make DT widely employed  for different applications that require a comprehension of both the  model construction and its prediction." />
      <node TEXT="First  the risk of trapping local  minima is reduced when several predictors are integrated. Further   when only a small amount of data is available  a single algorithm can  choose an incorrect hypothesis  which provides additional ability to  handle small size data scenarios. A tree decision model was chosen to be the  outputted model since it can be explained both in terms of its graphic  prediction structure as well as its separability." />
      <node TEXT="3 Puxeddu MG  Petti M  Astolfi L. A comprehensive analysis of multilayer  community detection algorithms for application to EEG based brain networks. 29  Deng L  Li J  Han Z. Online defect detection and automatic grading of carrots  using computer vision combined with deep learning methods. 32  Idowu OP  et al. An integrated deep learning model for motor intention  recognition of multi class EEG Signals in upper limb amputees." />
      <node TEXT="Through  our understandable prediction and feature selection phase  it is possible  to determine which features of datasets were more important in pre  diction. 2 This paper proposes an artificial intelligence decision system to  provide physicians with a simple and human interpretable set of  rules for diagnosing COVID 19 positive cases in the same spirit as  Decision Tree model together with social graph visualization to  ensure transparency and explainability for any clinician. 5 Though decision forest has a high level of prediction performance  its  inherent limitations cannot be hidden as well." />
      <node TEXT="In this developed model  an explainable decision forest classifier is employed to COVID 19  classification based on routinely available patient blood test data. As a result  it remains important to screen patients suspected of being infected with COVID 19. Reverse transcription  polymerase chain reaction  referred RT PCR  is currently the gold  standard for COVID 19 screening and is uniquely recommended by  World Health Organization  WHO   but it has main defects as well  delay  on turnaround times  5   a deficiency of reagents  6   suffers from a low  sensitivity  60 71    7   longer waiting time for the results  6 8   a high  false negative rate of 15 20   6   the need for certified laboratories  6    costly equipment  9   and requiring specialist staff  6 ." />
      <node TEXT="It should be noted that the features of this listed are sorted based on  their importance values  FIs . Table 4  Number of times the best results are achieved by different prediction models in  30 independent runs. Number Feature  1 PLT  2 EOS  3 MPV  4 CRP  5 AST  6 CREAT  7 WBC  8 MONO  9 LYM  10 RBC  11 NEU  12 NA  13 ALT  14 HCT  15 HGB  16 RWD  17 UREA  18 K  19 MCV  20 MCH  21 MCHC  M. Rostami and M. Oussalah" />
      <node TEXT="The authors show that SVC  Per  ceptron  Passive Aggressive Classifier  and Logistic Regression can  achieve higher than 98  prediction rate in Sentiment Analysis. The authors developed a clinically useful and easily interpretable  DT based model to help clinicians rapidly identify COVID 19 patients  with high mortality risks. The deep neuroevolution algorithm developed in this  paper is tested on a real world dataset  and its performance was indi  cated by comparing different evaluation metrics." />
      <node TEXT="As opposed to previous explainable artificial intelligence models that  analyzed local and post hoc explanations  our method explains the  entire dataset  global explanation  through a single model. The developed FSXRF achieves both explainability and feature  optimization  which are known to enhance attractiveness in medical  diagnosis. Paper Technique Task Data type Accuracy Explainability  Mahdy et al.   46  SVM Covid 19 lung image  classification X ray image High Low  Yu et al.  47   Decision Tree Severity detection of COVID 19  paediatric cases Chest radiography and CT images Medium High  Too and  Mirjalili   48 ." />
      <node TEXT="Then  given the deci  sion set D   xiCyi   xi RmCyi 1C Cc   a DT classifier is defined as  T xC CF   where F denotes the used features in tree    contains a set of  rules and x is an input sample. For fair experiments  different models should be evaluated on the  same training  validation and testing dataset. urine  e.g. Esterase  Aspect  He  moglobin  Ketone Bodies  Density  Protein  Leukocytes  Red blood cells   Granular cylinders  etc." />
      <node TEXT="Comparison with other explainable RF based models  RFs integrate multiple DTs towards providing a single output in su  pervised prediction duties. Moreover  when   is set to  a low value  the number of features will be reduced. 10.Average performance  in    over 30 independent runs  with different    values for Accuracy  F1 Score  Sensitivity and Specificity measures." />
    </node>
    <node TEXT="health">
      <node TEXT="In this developed model  an explainable decision forest classifier is employed to COVID 19  classification based on routinely available patient blood test data. As a result  it remains important to screen patients suspected of being infected with COVID 19. Reverse transcription  polymerase chain reaction  referred RT PCR  is currently the gold  standard for COVID 19 screening and is uniquely recommended by  World Health Organization  WHO   but it has main defects as well  delay  on turnaround times  5   a deficiency of reagents  6   suffers from a low  sensitivity  60 71    7   longer waiting time for the results  6 8   a high  false negative rate of 15 20   6   the need for certified laboratories  6    costly equipment  9   and requiring specialist staff  6 ." />
      <node TEXT="18  because of the  identified correlation between parameters such as white blood cells   neutrophils  lymphocytes  basophils  monocytes and others with  COVID 19 patients  6 . This demand is even  more stressed in healthcare sector where any diagnostic error can have  fatal consequences on patient life. How to balance  accuracy  explainability  and other factors of artificial intelligence in  medical applications remains a challenge today." />
    </node>
    <node TEXT="healthcare">
      <node TEXT="18  because of the  identified correlation between parameters such as white blood cells   neutrophils  lymphocytes  basophils  monocytes and others with  COVID 19 patients  6 . This demand is even  more stressed in healthcare sector where any diagnostic error can have  fatal consequences on patient life. How to balance  accuracy  explainability  and other factors of artificial intelligence in  medical applications remains a challenge today." />
    </node>
  </node>
</map>
