<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="healthcare">
      <node TEXT="Telemedicine can significantly contribute to healthcare in underserved  areas through telestroke  telecardiology  teledermatology  tele  pediatrics  telepsychiatry  and teleneonatology. So  telemedicine can  be utilized in three the health care aspect  including prevention  edu  cation  and treatment. The authors   title  journal  year of publication  and abstract for each article were  collected in an Excel  Microsoft Office 2019  spreadsheet." />
      <node TEXT="45  Saigi Rubi  o F  Jim enez Zarco A  Torrent Sellens J. Determinants of the intention to  use telemedicine  evidence from primary care physicians. 48  Pereyra Rodriguez JJ  Jim enez Zarco AI  Saig  Rubi  o F.  Factors that determine  the intention to use telemedicine in a healthcare organisation . 52  Almojaibel AA  Munk N  Goodfellow LT  Fisher TF  Miller KK  Comer AR  et al.  Development and validation of the tele pulmonary rehabilitation acceptance scale." />
      <node TEXT="1.Introduction  Telemedicine technology provides healthcare services in situations  where distance is a determinant factor. Specialized staff use telecom   munications technologies to exchange valid information for the diag  nosis  treatment  and prevention of disease and injury  as well as for  continuing education concerning health of the needy  1 3 . Some distinguish telemedicine from telehealth  which was previ   ously restricted to service delivery by physicians only and the telehealth  representing services provided by health professionals in general   including nurses  pharmacists  and others." />
    </node>
    <node TEXT="health">
      <node TEXT="4 Nakajima I  Sawada Y  Maeda T  Martin DL  Nagano S  Hamano N. Telemedicine  using small satellite MEO HICAT for international medical communications. 21  Garavand A  Samadbeik M  Nadri H  Rahimi B  Asadi H. Effective factors in  adoption of mobile health applications between medical sciences students using  the UTAUT model. 24  Wells G  Shea B  O Connell D  Peterson J  Welch V  Losos M  et al. Newcastle   Ottawa quality assessment scale cohort studies." />
      <node TEXT="45  Saigi Rubi  o F  Jim enez Zarco A  Torrent Sellens J. Determinants of the intention to  use telemedicine  evidence from primary care physicians. 48  Pereyra Rodriguez JJ  Jim enez Zarco AI  Saig  Rubi  o F.  Factors that determine  the intention to use telemedicine in a healthcare organisation . 52  Almojaibel AA  Munk N  Goodfellow LT  Fisher TF  Miller KK  Comer AR  et al.  Development and validation of the tele pulmonary rehabilitation acceptance scale." />
      <node TEXT="First  3766 publications    titles and abstracts were assessed together by three authors. Other surviving common models performed among physicians  include UTAUT  TIB  NPT  and so on. Mobile health and telerehabilitation are other types of telemedicine that  have been ranked with three studies  and the perceived usefulness factor  is the most important accepted factor in this type of telemedicine." />
      <node TEXT="1.Introduction  Telemedicine technology provides healthcare services in situations  where distance is a determinant factor. Specialized staff use telecom   munications technologies to exchange valid information for the diag  nosis  treatment  and prevention of disease and injury  as well as for  continuing education concerning health of the needy  1 3 . Some distinguish telemedicine from telehealth  which was previ   ously restricted to service delivery by physicians only and the telehealth  representing services provided by health professionals in general   including nurses  pharmacists  and others." />
      <node TEXT="Informatics in Medicine Unlocked 30  2022  100943 4Table 2  Publications related to the acceptance of telemedicine among physicians. 10 Kifle et al.  38  2010 Ethiopia TAM  TPB  UTAUT Telemedicine Self efficacy  compatibility   perceived ease of use  perceived  usefulness  social influence   anxiety The Perceived voluntariness has  a negative impact  11 Gagnon  M. P  et al.  39  2011 Spain TAM Telemonitoring Perceived usefulness  facilitators    12 Parra et al.  40  2012 Spain TAM TeleStroke Perceived usefulness and  perceived ease  Subjective norm   facilitating conditions  intention  to use    13 Rho MJ  Choi IY   Lee J  41  2014 South Korea TAM Telemedicine Perceived usefulness  perceived  ease of use  the accessibility of  medical records and of patients   self efficacy  perceived  incentives    14 Saig  Rubi  o  et al.  42  2014 Spain   Colombia   Bolivia Extended TAM Telemedicine Level of ICT use in personal life   perceived Ease of use   Propensity to innovate    15 Zailani.S et al.   43  2014 Malaysia Extended TAM Telemedicine Government policies  top  management support  perceived  usefulness  computer self   efficiency  health culture Moderating role of health  culture on the relationship  between government policies as  well as perceived usefulness on  telemedicine acceptance by  Malaysian hospitals  16 Dany  F    R omer  B  11  2014 Germany TAM Telemedicine Physicians   technological  contexts  data security and data  reliability   financial contexts   billability and costs   individual  contexts  technology affinity   subjective norms and  motivations   and organizational  contexts  compatibility of  telemedicine systems with  existing processes     17 Kuang Ming Kuo  et al.  44  2015 Taiwan Theory of Planned  Behavior TPB  Telemedicine Attitude  AT   subjective norm   SN   perceived behavioral  control  PBC  According to the results  our  study suggests that differing  strategies for experienced and  inexperienced physicians must  be formulated to substantially  boost the adoption of  telemedicine technology. 18 Saigi Rubi  o F  et al.  45  2016 Spain Extended TAM Telemedicine Security  confidentiality   reduced cost  the patients    predisposition Patients and medical staffs can  influence acceptance through  the factor of subjective norm." />
      <node TEXT="Telemedicine can significantly contribute to healthcare in underserved  areas through telestroke  telecardiology  teledermatology  tele  pediatrics  telepsychiatry  and teleneonatology. So  telemedicine can  be utilized in three the health care aspect  including prevention  edu  cation  and treatment. The authors   title  journal  year of publication  and abstract for each article were  collected in an Excel  Microsoft Office 2019  spreadsheet." />
      <node TEXT="Perceived usefulness Sample studies are from several  countries  29 Klingb et al.  56  2020 Dar Es  Salaam   Tanzania TAM M health technology for  emergency care of burn  patients Compatibility  Perceived  usefulness Most of the factors used in the  study  such as image  sound   perceived ease of use  Self   efficacy  Voluntariness  Anxiety   Social influences  Facilitating  conditions were not effective. 30 Lucia et al.  57  2020 USA  Brazil Researcher made Telemedicine Policy  culture  privacy Security was not effective. 31 Nguy et al.  58  2020 Canada TAM Telehealth applications in  palliative care perceived usefulness enabling  remote connection and  information sharing platform   and ease of use  integration with  existing IT systems and user   friendly with ready access to  technical support  User friendliness has been the  most important acceptance  factor  32 Haun eta l  59  2020 Germany Diffusion of  Innovations Theory   DIT  Video based integrated  care models featuring  mental health specialist  video consultations   MHSVC  the availability of a designated  room    33 Kissi et al.  60  2020 China TAM Telemedicine Perceived ease of use  perceived  usefulness These factors led to increased  efficiency  quality of services   quality patient care delivery   and satisfaction among  physicians  34 Cao et al.  61  2020 China Elaboration  likelihood model  and Trust transfer  theory The promotion of mobile  online health community   MOHC  Doctor s initial trust  doctor s  information quality  trust in  offline doctors  health service   service quality  MOHC  platform s initial trust." />
      <node TEXT="In our study  new factors are observed that  despite their low  frequency in the study  seem to be very important and should be given  much attention in telemedicine acceptance studies with the COVID 19  pandemic  such as government policies  relative advantage  top man  agement support  patient  s and doctor  s initial trust the patients   pre  disposition  and trialability. 5.Conclusion  Telemedicine is still a rich field for more innovation and investment   and it will bring more opportunities as a new technology that improves  the quality of telemedicine services in the coming years. TAM and TAM2 models offer a number of  obtained factors such as perceived usefulness  attitude  compatibility   perceived ease of use  self efficacy  subjective norm  perceived behav   ioral control  facilitating condition  health culture  reduced cost  secu  rity  and government policies which can be utilized as a behavioral and  individual model  in addition to contextual factors  to examine the  acceptance of telemedicine among doctors." />
    </node>
    <node TEXT="model">
      <node TEXT="Perceived usefulness Sample studies are from several  countries  29 Klingb et al.  56  2020 Dar Es  Salaam   Tanzania TAM M health technology for  emergency care of burn  patients Compatibility  Perceived  usefulness Most of the factors used in the  study  such as image  sound   perceived ease of use  Self   efficacy  Voluntariness  Anxiety   Social influences  Facilitating  conditions were not effective. 30 Lucia et al.  57  2020 USA  Brazil Researcher made Telemedicine Policy  culture  privacy Security was not effective. 31 Nguy et al.  58  2020 Canada TAM Telehealth applications in  palliative care perceived usefulness enabling  remote connection and  information sharing platform   and ease of use  integration with  existing IT systems and user   friendly with ready access to  technical support  User friendliness has been the  most important acceptance  factor  32 Haun eta l  59  2020 Germany Diffusion of  Innovations Theory   DIT  Video based integrated  care models featuring  mental health specialist  video consultations   MHSVC  the availability of a designated  room    33 Kissi et al.  60  2020 China TAM Telemedicine Perceived ease of use  perceived  usefulness These factors led to increased  efficiency  quality of services   quality patient care delivery   and satisfaction among  physicians  34 Cao et al.  61  2020 China Elaboration  likelihood model  and Trust transfer  theory The promotion of mobile  online health community   MOHC  Doctor s initial trust  doctor s  information quality  trust in  offline doctors  health service   service quality  MOHC  platform s initial trust." />
      <node TEXT="First  3766 publications    titles and abstracts were assessed together by three authors. Other surviving common models performed among physicians  include UTAUT  TIB  NPT  and so on. Mobile health and telerehabilitation are other types of telemedicine that  have been ranked with three studies  and the perceived usefulness factor  is the most important accepted factor in this type of telemedicine." />
      <node TEXT="4 Nakajima I  Sawada Y  Maeda T  Martin DL  Nagano S  Hamano N. Telemedicine  using small satellite MEO HICAT for international medical communications. 21  Garavand A  Samadbeik M  Nadri H  Rahimi B  Asadi H. Effective factors in  adoption of mobile health applications between medical sciences students using  the UTAUT model. 24  Wells G  Shea B  O Connell D  Peterson J  Welch V  Losos M  et al. Newcastle   Ottawa quality assessment scale cohort studies." />
      <node TEXT="In our study  new factors are observed that  despite their low  frequency in the study  seem to be very important and should be given  much attention in telemedicine acceptance studies with the COVID 19  pandemic  such as government policies  relative advantage  top man  agement support  patient  s and doctor  s initial trust the patients   pre  disposition  and trialability. 5.Conclusion  Telemedicine is still a rich field for more innovation and investment   and it will bring more opportunities as a new technology that improves  the quality of telemedicine services in the coming years. TAM and TAM2 models offer a number of  obtained factors such as perceived usefulness  attitude  compatibility   perceived ease of use  self efficacy  subjective norm  perceived behav   ioral control  facilitating condition  health culture  reduced cost  secu  rity  and government policies which can be utilized as a behavioral and  individual model  in addition to contextual factors  to examine the  acceptance of telemedicine among doctors." />
      <node TEXT="Given that there are different types of  telemedicine  they seem to be general and ambiguous studies. Therefore  the use and strengthening of this factor among physi   cians should be done with caution. In a comprehensive systematic review study on the use of the Table 3  Frequency of acceptance models as a basis for telemedicine acceptance among  physicians." />
    </node>
  </node>
</map>
