<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="model">
      <node TEXT="The AI driven IoT  AIIoT  for smart health  care is able to revolutionize a number of aspects within the health care  industry  however  a number of technical concerns must be addressed  before such potential is achieved  3 . The purpose of this research is to outline AI driven IoT  AIIoT  se  curity  including authentication  access control  security models  and  privacy issues. The present essay addresses AI driven IoT  AIIoT   security in smart health care and medical devices." />
    </node>
    <node TEXT="health">
      <node TEXT="By  applying this parallel  it can be inferred that even if the data transmitted  by a given endpoint device might not result in any issue related to pri  vacy  per se  the amount of data that is accumulated from different de  vices can also create some types of privacy problems  10 . Choi et al. illustrated the IoT com  ponents  respective vulnerabilities and threat attack type  as summarized in Table 1. A good example to explain such privacy breaches  includes the case of a group of insurance commissions in Massachusetts   which bought health insurance for state employees and released records  for every hospital visit by the state employees at no cost to any scholar  who wanted such data  13 ." />
      <node TEXT="However  scholars argue that even  such methods might not guarantee anonymization and protection of  sensitive personal data  20 . AI driven IoT has evolved from traditional statis   tical algorithms to neural networks that are somewhat artificially com  plex. Privacy issues IoT based solutions  PHRS exposure Encryption before outsourcing  dividing health  system into domains  analyzing sensitive data to be  private or not." />
      <node TEXT="The AI driven IoT  AIIoT  for smart health  care is able to revolutionize a number of aspects within the health care  industry  however  a number of technical concerns must be addressed  before such potential is achieved  3 . The purpose of this research is to outline AI driven IoT  AIIoT  se  curity  including authentication  access control  security models  and  privacy issues. The present essay addresses AI driven IoT  AIIoT   security in smart health care and medical devices." />
      <node TEXT="In conclusion  it is evident that the AI driven IoT frameworks used  both in smart medical devices are highly susceptible to different forms of  security and privacy threats  therefore  there exist many security and  privacy challenges as well as relevant requirements that all must be  addressed. It is true that AI driven IoT has a great ability to  transform the way in which we live today. Reference   1 Butpheng C  Yeh K H  Xiong H. Security and privacy in IoT cloud based e health  systems a comprehensive review." />
      <node TEXT="To outline the type of security  privacy  and trust measures that  should be taken when applying AI driven IoT  AIIoT  for smart  health care systems. The researcher made a search of different peer reviewed articles from  various databases  which included Google Scholar  EBSCOhost  ERIC   and Academic OneFile. Words such as  Information Security Culture     privacy     AI   driven IoT   and  Smart health care  were used in the search process." />
    </node>
  </node>
</map>
