<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="model">
      <node TEXT="To validate that activation of NF B correlated  with NF B induced gene transcription we assessed IL 1  gene expression  by quantitative reverse transcriptase PCR  qRT PCR  in THP 1 cells  treated with LPS or flagellin. Experimental and modeling data for the dual TLR signaling cascades  Since cells rarely receive a single signal at any given time there was  interest in creating a more realistic experimental system utilizing mul  tiple agonists  LPS and flagellin. To create more complex models that could react to multiple agonists   a new algorithm was developed that combined the TLR4 and TLR5  models into a dual signaling model  Fig." />
      <node TEXT="Analysis of dual signaling reveals greater complexity at the  transcriptional level  To further investigate NF B induced transcriptional regulation upon  dual signaling expression of two additional genes  IL 6 and TNF     were  quantified. However  when the cells were exposed to both LPS  and flagellin IL 6 and TNF    gene expression did not show the same  pattern as IL 1  gene expression or NF B activation  Figs. 4.Discussion  Modeling can provide data that not only contributes to the under   standing of complex signaling cascades  but can also be informative of  what experiments should be done next  can be used to make predictions  about the best targets in a signaling cascade to increase or decrease the  desired cell response  and provide information about how cells or even  patients may respond to pharmacological interventions." />
      <node TEXT="25  Smith M  Garc a Mart nez E  Pitter MR  Fucikova J  Spisek R  Zitvogel L   Kroemer G  Galluzzi L. Trial Watch  toll like receptor agonists in cancer  immunotherapy. 28  Patra MC  Kwon H  Batool M  Choi S. Computational insight into the structural  organization of full length toll like receptor 4 dimer in a model phospholipid  bilayer. 33  Goff PH  Hayashi T  He W  Yao S  Cottam HB  Tan GS  Crain B  Krammer F   Messer K  Pu M  Carson DA  Palese P  Corr M. Synthetic toll like receptor 4  TLR4   and TLR7 ligands work additively via MyD88 to induce protective antiviral  immunity in mice." />
      <node TEXT="This is an open access article under the CC BY NC ND license   http   creativecommons.org licenses by  nc nd 4.0   .An experimental and computational approach to unraveling interconnected  TLR signaling cascades  Chun Wai Liewa  Laura Polancob  Kimberly Manalangb  Robert A. Kurtb    aDepartment of Computer Science  Lafayette College  Easton  PA  18042  USA  bDepartment of Biology  Lafayette College  Easton  PA  18042  USA    ARTICLE INFO   Keywords   Computer modeling  Dual TLR signaling  Interconnected cascades ABSTRACT   Previously  a modeling tool was used to construct a model of the TLR4 signaling cascade  and here the utility of  the modeling tool in two dimensions   adaptability  different types of TLR cascades and readout systems  and  power  the ease with which models of more complex cascades could be created by combining simpler inter  connected cascades  was evaluated. This initial encounter is facilitated by pattern  recognition receptors  PRRs  on innate white blood cells such as mac  rophages  neutrophils  and dendritic cells which recognize pathogen  associated molecular patterns  PAMPs  on potential pathogens  1 3 . Upon binding to LPS  TLR4 forms a homodimer bringing  together the Toll interleukin  IL  1R homology  TIR  domains of TLR4  and Myd88." />
      <node TEXT="The simulation model  also did not respond in a synergistic manner when stimulated with both  agonists  Fig. All data are the average and standard error of at least three separate experiments. Where indicated     significant differences were  found relative to the control  0  g ml LPS  at each dose p D0.05 using a Student  s t Test ." />
      <node TEXT="However  since pathogens have  more than one PAMP  a more biologically relevant experimental system  and model should take into account what happens when multiple TLRs  are activated in the same cell at the same time. For  instance  cancer therapies that target multiple pathways  24 25 31 32   may be more successful than targeting a single pathway. All data are the average and standard error of at least three separate experiments." />
    </node>
  </node>
</map>
