<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="model">
      <node TEXT="Informatics in Medicine Unlocked 30  2022  100948 3structure was uploaded to the GalaxyRefine online web based server. Disulfide by Design 2.0  48  was used to assign such bonds for the  designed vaccine. The binding stability and flexibility of  the protein and ligand complex was analyzed using iMODS server   http   imods.Chaconlab.org    which performs Normal Mode Analysis   NMA  in internal  dihedral  coordinates using an elastic network model   ENM   54 . In this circumstance  we employed a minimum interval of 30 days  between two doses  as previously specified  56 . With the maximum simulation step value set to 300  all other stimulation  parameters were left at their default settings. Analysis of the proteins  After analyzing proteomic data three proteins RNA dependent RNA  polymerase  RdRp   polyprotein  PP   and major capsid protein VP2   MCPVP2  of marine birnavirus  MABV  were selected  as they were  found non allergen. We predicted the transmembrane helices of these three proteins  in a suitable number  Table 1 ." />
      <node TEXT="With  other parameters such as energy and the chi3 value taken into account   two pairs of mutations with cysteine were recommended. Molecular docking research  To predict their binding affinity and interactions  the vaccine   ligand  and TLR5  receptor  were docked. As a result  the ClusPro v2.0  server produced nine docked complexes in various positions. As a consequence  model 7  satisfied the inclination requirement. A total of 3 hydrogen bonds were found on Table 1  Details of the Antigenic vaccine candidate proteins. NCBI Gene Bank Sub cellular localization Transmembrane Helices Antigenicity  Polyprotein YP 010086267.1 Plasma membrane 0 0.5008  RNA dependent RNA polymerase YP 010086266.1 Interact with DNA 0 0.4093  Major capsid protein VP2 AAQ82705.1  title   ncbi p AAQ82705.1  FAAQ82705.1 Outer capsid 0 0.4965   Table 2  Final CTL epitopes used to construct MEBV. Characteristics Finding Remark  Number of amino acids 255 Suitable  Molecular weight 26638.28 Average  Theoretical pI 4.82 Acidic  Chemical formula C1196H1900N302O375S4    Instability index of vaccine 17.36 Stable  Aliphatic index of vaccine 88.35 Thermostable  Grand average of hydropathicity   GRAVY  0.013 Hydrophobic  Antigenicity 0.6964 Antigenic  Immunogenicity Positive Immunogenic  Allergenicity No Non allergen  Solubility 0.81177 Soluble   Table 4  Secondary structural properties of the vaccine." />
      <node TEXT="The multi epitope docked vaccine candidate RMSF plot. Red and blue backgrounds  emphasize the alpha helical and beta strand sections  respectively. These areas are defined by helices or strands that last for 70  of the simulation time. For  interpretation of the references to color in this figure legend  the reader is referred to the Web version of this article. 8.The molecular dynamics simulation of the Vaccine  TLR5 docked complex  A  Deformability simulations on main chains show high deformability in hinges   B  Normal mode analysis generates B factor values  which measure each atoms uncertainty  C  The eigenvalue of the docked complex  showing the energy required  to deform the structure  D  The variance matrix between complex and residue  E  The covariance matrix between pairs of residues  red  correlated  white  un  correlated  blue  anti correlated   F  The elastic network model  which suggests that atoms and springs are linked. Stiff springs have a darker grey color. For  interpretation of the references to color in this figure legend  the reader is referred to the Web version of this article." />
    </node>
  </node>
</map>
