<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="health">
      <node TEXT="Undoubtedly  information technology is one of the most  advanced sciences for dealing effectively with Covid 19  5 . Due to their nature  national dash  boards can be effective in managerial and health aspects  31 . Its various  users can obtain their information at the national level and specific re  gions." />
      <node TEXT="This is an open access article under the CC BY NC ND license   http   creativecommons.org licenses by  nc nd 4.0   .Applications  features and key indicators for the development of Covid 19  dashboards  A systematic review study  Akram Vahedia  Hamid Moghaddasia  Farkhondeh Asadia    Azam Sadat Hosseinia   Eslam Nazemib  aDepartment of Health Information Technology and Management  Faculty of Paramedical Sciences  Shahid Beheshti University of Medical Sciences  Tehran  Iran  bComputer Engineering Faculty  Shahid Beheshti University  Tehran  Iran    ARTICLE INFO   Keywords   Dashboard  COVID 19  Data management ABSTRACT   Introduction  Interactive dashboards can collect data from various information sources and be used nationally and  internationally. These information systems have played an important role in managing and controlling epidemic  diseases  especially Covid 19. This study aimed to identify the applications  features  and key indicators of  advanced dashboards in Covid 19." />
      <node TEXT="Informatics in Medicine Unlocked 30  2022  100910 2comprehensive  meaningful  and intelligent way using visual features in  the form of key performance indicators for faster decision making so that  managers to be able to take a brief look at the current situation in terms  of whether the evaluation performance is desirable or undesirable   identify existing problems and analyze their root causes  and finally   improve their performance  12 13  . Although all the dashboards studied included epidemiolog   ical indicators  a limited number of them stated their main purpose and  intended users. In another study  Ibrahim et al.  conducted a study to develop and use a clinical intelligent dashboard for  frontline physicians to optimize important resources along covid 19   which could interact and receive information from the electronic  health record  EHR   21 ." />
    </node>
  </node>
</map>
