<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="health">
      <node TEXT="Several metabolic comorbidities like polycystic ovarian syndrome  PCOS    type 2 diabetes  T2D   obesity  and cardiovascular disease  CVD  have been associated with female infertility   FI . Here  we have used differentially  expressed genes  DEGs  to uncover various biological targets for a better understanding of FI and metabolic  comorbidities development. Female infertility is  defined as the inability to become pregnant after a year or more of un  protected intercourse  1 . Later life health risk  development such as polycystic ovarian syndrome  PCOS   cardiovas   cular disease  CVD   type 2 diabetes  T2D   and obesity could be an early  indication of female infertility  5 . Infertility in women can be caused by a medical condition that  damages the fallopian tubes  impairs ovulation  or triggers hormonal  problems. The genetic etiology for infertility defined by anomalies in human  egg development  fertilization  and early embryogenesis is not  completely explained. However  numerous investigations have shown  possible gene alterations including PADI6  10   TUBB8  11   Biallelic  Abbreviations  FI   Female Infertility  CVD   Cardiovascular Disease  T2D   Type 2 Diabetes  PCOS   Ploycystic Ovarian Syndrome  DEG   Differential Expressed  Gene  TF   Transcription Factor  MCC   Maximum Clique Centrality  MNC   Maximum Neighborhood Component  IVF   Invitro Fertilization  FFA   Free Fatty Acid   GO   Gene Ontology  OBS   Obesity  PPI   Protein Protein Interaction  SCMC   Subcortical Maternal Complex." />
    </node>
    <node TEXT="model">
      <node TEXT="The most significant molecular pathways  including adipocytokine signaling pathway  pathway cancer  MAPK  family signaling cascades  and Jak stat signaling pathways were iden  tified in our study and were displayed in Fig. The model is designed to show how numerous  disorders interact through gene regulation and biological processes. The PPI network of common DEGs is depicted in  Fig. Several associated nodes  in a PPI network are designated as hub proteins at the same time. Using  four different approaches  including degree  maximum neighborhood  Fig. 6.The Enriched  A  KEGG and  B  WIKI pathways are generated from common differentially expressed genes. 7.Protein protein interaction network for common shared DEGs using cut off value 900." />
      <node TEXT="We have identified several essential GO pathways in this study  including calcium ion transport  regulation of acute inflammatory  response  an integral component of the plasma membrane  and intra   molecular oxidoreductase activity which are related to FI and other  metabolic commodities. In their investigation  Ji Shen et al. identified  several GO factors including chromatin remodeling  positive transcript  factor regulation  regulation of smooth cell differentiation  and oxida   tive DNA methylation  61   while another study conducted by Weidong  Zhou also discovered significant GO pathways such as regulation of  transcription and gene expression  biosynthetic processes and cell  development  62  were associated to FI development. Besides  recent studies also show that in women with endometriosis  the MAPK signaling pathway is  hyperactive  63 . A PPI network was built by our research employing common dif  ferential genes based on STRING databases. Such identified hubs pro  teins can be used to identify potential drug targets or biomarkers using  topological analysis techniques. Several  ApoC3 gene variants have been linked to the development of insulin  Fig. 9.TF   Dysregulated Genes between FI and figure  A  T2D   B  CVD   C  Obesity  D  PCOS." />
      <node TEXT="In Cytoscape  two FI based interaction networks were constructed to  discover statistically significant correlations between these metabolic  diseases. 4 depict the relationship be  tween gene disease networks at over and under expressed levels. Annotation and ontology are  also designed to carry out a sophisticated biological structure model  which is commonly employed in biological applications  57 . The  database was used as an annotation source for the gene ontology study  which was done in three areas  biological process  cellular component   and molecular function . Calcium ion transport  regulating acute in  flammatory response  an integral part of the plasma membrane  and  intra molecular oxide reductase activity are the most often used GO  Fig. 5.Functional enrichment analysis of the differential expressed genes in FI and metabolic comorbidities. In figure  A  BP   B  CC  and  C  MF indicates each of the  GO processes was plotted based on the  log p value." />
      <node TEXT="To investigate the impact of FI and its genetic relationship with  other metabolic comorbidities  we collected and analyzed relevant  microarray datasets from the National Center for Biotechnology Infor  mation Gene Expression Omnibus database. In our study  5 different  microarray datasets were analyzed  including Female Infertility  FI    Polycystic ovary syndrome  PCOS   Type 2 diabetes  T2D   Obesity   OBS   and Cardiovascular disease  CVD  with the accession numbers of  GSE92324  GSE5850  GSE16415  GSE48521  and GSE24519. The Z score transforms a  popular method for normalizing gene expression matrices  36 38 . This transformation  allows for a straightforward comparison of gene expression data in  various models and disorders. We have used an unpaired t test  with a p value D0.05 and a complete log fold change  log2FC F1  to  look if any genes are expressed differentially between the disease and  control state  39 . Using NCBI  s GEO2R online tool  40   all datasets  from the NCBI GEO database were studied and discriminated with the  typical subject to recognize consistent genes expressed differentially. Finally  the gene disease  association network  GDN  was created and visualized in Cytoscape  v3.8.2  42 ." />
    </node>
    <node TEXT="machine learning">
      <node TEXT="16  Parikh NI  Jeppson RP  Berger JS  Eaton CB  Kroenke CH  LeBlanc ES  Lewis CE   Loucks EB  Parker DR  Rillamas Sun E  Ryckman KK. 18  Morgante G  Massaro MG  Di Sabatino A  Cappelli V  De Leo V. Therapeutic  approach for metabolic disorders and infertility in women with PCOS. Bioinformatics and machine learning methodologies to identify the effects of  central nervous system disorders on glioblastoma progression. 49  Fornes O  Castro Mondragon JA  Khan A  Van der Lee R  Zhang X  Richmond PA   Modi BP  Correard S  Gheorghe M  Barana  si c D  Santana GarciaW. 53  Arju Hossain Md  Sohel Md  Rahman MdH  Hasan MdI  Khan MdS  Amin MdAl   et al. Bioinformatics and in silico approaches to identify novel biomarkers and  key pathways for cancers that are linked to the progression of female infertility  a  comprehensive approach for drug discovery. 60  Shen J  Chen L  Cheng J  Jin X  Mu Y  Li Q  Xia L  Gao Y  Xia Y. Circular RNA  sequencing reveals the molecular mechanism of the effects of acupuncture and  moxibustion on endometrial receptivity in patients undergoing infertility  treatment. Endometrial receptivity in the eutopic endometrium of women  with endometriosis  it is affected  and let me show you why." />
    </node>
  </node>
</map>
