<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="model">
      <node TEXT="Downscaling the image will  result in a more efficient processing model by reducing computational  complexity and memory consumption. This can be done  through several techniques  such as rotation and flipping of images. Study Main Objective Dataset Method Algorithm Results   1  Predict the maxillary canine  impaction using sectors and  angular measurement methods." />
      <node TEXT="Informatics in Medicine Unlocked 30  2022  100918 6Finally  using a CNN model does not require intensive preprocessing   as it can observe fine grained patterns efficiently. The third  step is pooling  also referred to as down sampling  which operates on  each feature map independently. The pre trained CNN ar  chitectures utilized in this study  DenseNet  VGG  Inception V3  and  ResNet 50  are discussed below." />
      <node TEXT="This is an open access article under the CC BY NC ND license   http   creativecommons.org licenses by  nc nd 4.0   .Canine impaction classification from panoramic dental radiographic images  using deep learning models  Malak Aljabria b    Sumayh S. Aljameelb  Nasro Min Allahb  Jawaher Alhuthayfib   Leena Alghamdib  Nouf Alduhailanb  Reem Alfehaidb  Reem Alqarawib  Muhanad Alharekyc   Suliman Y. Shahind  Walaa Al Turkic  aComputer Science Department  College of Computer and Information Systems  Umm Al Qura University  Makkah 21955  Saudi Arabia  bDepartment of Computer Science  College of Computer Science and Information Technology  Imam Abdulrahman Bin Faisal University  P.O. Four deep  learning models were developed to classify the type of canine impaction from panoramic dental radiographic  images  DenseNet 121  VGG 16  Inception V3  and ResNet 50. E mail addresses  mssjabri uqu.edu.sa   msaljabri iau.edu.sa  M. Aljabri   saljameel iau.edu.sa  S.S. Aljameel   nabdullatief iau.edu.sa  N. Min Allah    2170005195 iau.edu.sa  J. Alhuthayfi   2170006635 iau.edu.sa  L. Alghamdi   2170002706 iau.edu.sa  N. Alduhailan   2170005031 iau.edu.sa   R. Alfehaid   2170006008 iau.edu.sa  R. Alqarawi   malhareky iau.edu.sa  M. Alhareky   sshahin iau.edu.sa  S.Y." />
      <node TEXT="In addition  the proposed model could  be applied and evaluated with a dataset that contains all seven types of  canine impaction. Funding  This work was supported by the Deanship of Scientific Research   Imam Abdulrahman Bin Faisal University  Dammam  Saudi Arabia   Grant No. 20  Lee J  Kim D  Jeong S  Choi S. Detection and diagnosis of dental caries using a deep  learning based convolutional neural network algorithm." />
      <node TEXT="Warford et al.  1  conducted a study to predict maxillary canine  impaction in its early stages using sectors and angular measurement  methods. To conclude  CNN is a widely used deep learning model in the  medical image processing and classification research field. One paper that applied deep learning for canine impaction classifi   cation was found ahead of this study  which used a different method   features  and classes." />
      <node TEXT="All four models in this  experiment did not perform well  as the highest accuracy achieved was  0.8095. Furthermore  Inception V3 achieved the highest ac  curacy 0.9259  using a balanced dataset with image resolution  enhancement. Accuracy Precision Recall Specificity F Score  Inception V3 0.8095 0.7143 0.4545 0.9355 0.5555  ResNet 50 0.7619 0.8249 0.7780 0.9216 0.8008  DenseNet 121 0.7976 0.7825 0.6219 0.9178 0.6930  VGG 16 0.6548 0.1000 0.0167 0.9305 0.0286  M. Aljabri et al." />
    </node>
  </node>
</map>
