<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="health">
      <node TEXT="According to the  World Health Organization  WHO   more than 500 000 new cases of  brucellosis are annually reported worldwide  4 . These interventions necessitate a consistent  reliable  and interoperable  dataset across involved organizations  8 9 . Contents lists available at ScienceDirect  Informatics in Medicine Unlocked  u   zkw  s yo kr o     1ow  o to 1m y2w m k o2ty   https   doi.org 10.1016 j.imu.2022.100953  Received 22 February 2022  Received in revised form 19 April 2022  Accepted 20 April 2022" />
      <node TEXT="3.Results  In the present study  after performing a literature review  data ele  ments required for reporting brucellosis were identified. In this stage  all factors related to brucellosis were extracted and a  pool of data was formed. Data items Content definition Field format  Patient name  string  Identification number  integer  Gender Male  Female  Male  1  Female  0  binary  Age  integer  Birth date  date  Marital status Married categorical  Single  Divorced  Widow  Other  unspecified  Occupation Job Laboratory worker categorical  Abattoir workers  Animal husbandry  Slaughterhouses  Veterinarians and Animal Caretakers  Farmers  agricultural engineers  animal dealers  cattle ranchers  Shepherds  Dog owners and handlers  Dairy workers  Other Occupations  Admission date  Date  Region Country string  Provence  City  Urban  Rural  Education level Illiterate categorical  Elementary  High school  University  Home address  string  Healthcare setting name  string  blood group type A   A  categorical  B   B   O   O   B   B   AB   AB    Rh type Rh   Rh   Rh  0  Rh   1  Binary  M. Shafiee et al." />
      <node TEXT="In another  study  Shanbehzadeh et al.  2022  designed a standard and customized  reporting template to provide interoperability between zoonotic dis  eases information systems  ZDISs  in Iran. Dong et al. reported that a standard brucellosis reporting template  improves data integrity  interoperability  accuracy  and reusability for  the patient care process  care quality  and research  55 . Moreover  Moradi et al. designed the  structure and content of the national brucellosis surveillance system for  Iran s electronic health  e health  system to improve epidemiological  studies and clinical research." />
      <node TEXT="Determining the MDS is a principal  and effective step in designing an information system that directly de  termines its failure or success  23 . Brucellosis MDS can guide clini  cians in structured reporting  improve patients   outcomes  and facilitate  further communication between healthcare organizations across the  country. All par  ticipants were required to sign a privacy agreement and study partici   pation consent form before joining the expert panel." />
    </node>
    <node TEXT="healthcare">
      <node TEXT="3.Results  In the present study  after performing a literature review  data ele  ments required for reporting brucellosis were identified. In this stage  all factors related to brucellosis were extracted and a  pool of data was formed. Data items Content definition Field format  Patient name  string  Identification number  integer  Gender Male  Female  Male  1  Female  0  binary  Age  integer  Birth date  date  Marital status Married categorical  Single  Divorced  Widow  Other  unspecified  Occupation Job Laboratory worker categorical  Abattoir workers  Animal husbandry  Slaughterhouses  Veterinarians and Animal Caretakers  Farmers  agricultural engineers  animal dealers  cattle ranchers  Shepherds  Dog owners and handlers  Dairy workers  Other Occupations  Admission date  Date  Region Country string  Provence  City  Urban  Rural  Education level Illiterate categorical  Elementary  High school  University  Home address  string  Healthcare setting name  string  blood group type A   A  categorical  B   B   O   O   B   B   AB   AB    Rh type Rh   Rh   Rh  0  Rh   1  Binary  M. Shafiee et al." />
      <node TEXT="Determining the MDS is a principal  and effective step in designing an information system that directly de  termines its failure or success  23 . Brucellosis MDS can guide clini  cians in structured reporting  improve patients   outcomes  and facilitate  further communication between healthcare organizations across the  country. All par  ticipants were required to sign a privacy agreement and study partici   pation consent form before joining the expert panel." />
    </node>
    <node TEXT="machine learning">
      <node TEXT="Further extensions and modifications are essential  thus  conducting  an experimental study by including a supplementary Delphi phase to  improve the dataset is recommended. Furthermore  this dataset can collect generalizable variables  from multi center organizations and lay the basis for conducting an  exhaustive analysis based on machine learning  ML  methods about  many aspects of brucellosis. This protocol is as follows   Authors  contributions  M SH  1  and H KA performed a literature review to define the MDS   brucellosis parameters." />
    </node>
  </node>
</map>
