<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="model">
      <node TEXT="A molecular modeling  approach to identify potential antileishmanial compounds against the cell  division cycle  cdc  2 Related kinase 12  CRK12  receptor of Leishmania  donovani. 32  Abraham MJ  Murtola T  Schulz R  P all S  Smith JC  Hess B  Lindah E. Gromacs   high performance molecular simulations through multi level parallelism from  laptops to supercomputers. 42  Ntie Kang F  Zofou D  Babiaka SB  Meudom R  Scharfe M  Lifongo LL  Mbah JA   Mbaze LM  Sippl W  Efange SMN. 45  Ntie Kang F  Telukunta KK  Doring K  Simoben CV  Moumbock AF  Malange YI   Njume LE  Yong JN  Sippl W  Gunther S. NANPDB  a resource for natural products  from northern african sources. 52  Sander T  Freyss J  von Korff M  Rufener C. DataWarrior  an open source program  for chemistry aware data visualization and analysis. 66  Kwofie SK  Dankwa B  Odame EA  Agamah FE  Doe LPA  Teye J  Agyapong O   Miller WA  Mosi L  Wilson MD. Computational identification of  potential anti inflammatory natural compounds targeting the p38 Mitogen   activated protein kinase  MAPK   implications for COVID 19 induced cytokine  storm." />
      <node TEXT="A current control method involves the mass  drug administration of synthetic drugs  mainly albendazole and mebendazole. Although  Necator americanus gluta   thione S transferase 3  Na GST 3  is a notable target  using natural product libraries for computational eluci  dation of promising leads is underexploited. A compendium  of 3182 African natural products together with five known helminth GST inhibitors including Cibacron blue was  screened against the active sites of the Na GST 3 structure  PDB ID  3W8S . Furthermore  the selected compounds formed key intermolecular interactions  with critical residues Tyr95  Gly13 and Ala14. Notably  ZINC85999636  ZINC14825190  and dammarane tri  terpene13 were predicted as anthelmintics  whilst all the four molecules shared structural similarities with  known inhibitors. Molecular modelling showed that the compounds had reasonably good binding free energies. Contents lists available at ScienceDirect  Informatics in Medicine Unlocked  u   zkw  s yo kr o     1ow  o to 1m y2w m k o2ty   https   doi.org 10.1016 j.imu.2022.100957  Received 28 December 2021  Received in revised form 9 April 2022  Accepted 25 April 2022" />
      <node TEXT="Analogues or derivatives of the predicted compounds can be explored  using techniques including pharmacophore modeling. 4 Hotez PJ  Bethony J  Bottazzi ME  Brooker S  Buss P. Hookworm   The great  infection of mankind. 6 Soukhathammavong PA  Sayasone S  Phongluxa K  Xayaseng V  Utzinger J   Vounatsou P  Hatz C  Akkhavong K  Keiser J  Odermatt P. Low efficacy of single   dose albendazole and mebendazole against hookworm and effect on concomitant  helminth infection in Lao PDR. 11  Diawara A  Halpenny CM  Churcher TS  Mwandawiro C  Kihara J  Kaplan RM   Streit TG  Idaghdour Y  Scott ME  Bas a nez M G  et al. Association between  response to albendazole treatment and   tubulin genotype frequencies in soil   transmitted helminths. 13  Vercruysse J  Albonico M  Behnke JM  Kotze AC  Prichard RK  McCarthy JS   Montresor A  Levecke B. 18  Williamson AL  Lecchi P  Turk BE  Choe Y  Hotez PJ  McKerrow JH  Cantley LC   Sajid M  Craik CS  Loukas A. Structure of monomeric Na GST 3  a glutathione S   transferase from the major human hookworm parasite Necator americanus." />
    </node>
  </node>
</map>
