<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="health">
      <node TEXT="These negative psychologi   cal feelings are associated with experiencing depression  anxiety  and  stress which can trigger mental disorders considering  31 32 . In another survey study  a preponderance of  depression  stress  and anxiety among the women was reported 28 . A different study conducted on healthcare  practitioners revealed no differences between male and female doctors  in the scores  39 . The present findings reported that stress  anxiety  and depression are  higher among younger people  18 30 years old . Similarly  a study  showed that individuals aged 40 years have higher stress levels  compared to those below the age of 40  39 . Holmes et al.  18   showed that older adults and those with low incomes  are susceptible to poor mental health. The cost of  implementing CBT can be significantly reduced using open source  learning platforms such Moodle  43 ." />
      <node TEXT="Acknowledgment  The authors would like to thank Jordan University of Science and  Technology for its support. 3 Xiong J  Lipsitz O  Nasri F  Lui LMW  Gill H  Phan L  et al. Impact of COVID 19  pandemic on mental health in the general population  a systematic review. 7 Wang C  Tee M  Roy AE  Fardin MA  Srichokchatchawan W  Habib HA  et al. 10  Huang Y  Zhao N. Generalized anxiety disorder  depressive symptoms and sleep  quality during COVID 19 outbreak in China  a web based cross sectional survey. Relationship of physical  activity with anxiety and depression symptoms in Chinese college students during  the COVID 19 outbreak. 20  Renaud Charest O  Lui LMW  Eskander S  Ceban F  Ho R  Di Vincenzo JD  et al.  Onset and frequency of depression in post COVID 19 syndrome  a systematic  review. The effect of cognitive behavioral  therapy on depression  anxiety  and stress in patients with COVID 19  a S. Abuhammad et al." />
      <node TEXT="Many Jordanians experienced moderate to  severe depression  stress  and anxiety during the COVID 19 era. The  public has experienced anxiety  depression  psychological distress   post traumatic stress disorder  and insomnia  3 4 . Similar findings were reported in studies that included several  countries from three continents  6 7 . Studies have shown that individuals experiencing  overwhelming emotional traumas and socioeconomic stressors during  COVID 19 were more vulnerable to committing suicide  12 13 . As argued by  Holmes et al.  18   older adults and those with low incomes are more  susceptible to poor mental health. In addition  a meta analysis showed  that people with pre existing mood disorders are at increased risk of  hospitalization and death for COVID 19 compared to the general pop  ulation  19 . Furthermore  it has been shown that the risk of depressive  symptoms persists for weeks after infection with COVID 19  20 ." />
      <node TEXT="Additionally  the relationship of age and gender with mental health  measures was examined. Further  individuals younger than 18 years old and those not residing in  Jordan were excluded from the study. All completed surveys were then saved on password protected  Google forms that the researcher could only access and fill by every  recipient. The survey was designed so that respondents were limited to  providing one response per individual. The scale is a reliable and valid  measure of mental health  23 . The DASS D scale is used to determine hopelessness  dysphoria  life  devaluation  self deprecation  inertia  and anhedonia among study  participants. The DASS  scores  Table 3  show significantly high scores for stress  anxiety  and  depression in the groups that perceived moderate to a high probability  of infection with COVID 19  P D0.05 ." />
      <node TEXT="Moodle  the cost effective solution for internet cognitive  behavioral therapy  I CBT  interventions. Mental health strategies to combat the psychological  impact of coronavirus disease 2019  COVID 19  beyond paranoia and panic. 46  Ho RC  Sharma VK  Tan BYQ  Ng AYY  Lui YS  Husain SF  et al. Comparison of  brain activation patterns during olfactory stimuli between recovered COVID 19 patients and healthy controls  a functional near infrared spectroscopy  fNIRS   study. 47  Husain SF  Yu R  Tang TB  Tam WW  Tran B  Quek TT  et al. Validating a functional  near infrared spectroscopy diagnostic paradigm for Major Depressive Disorder. 48  Husain SF  Tang TB  Yu R  Tam WW  Tran B  Quek TT  et al. Cortical  haemodynamic response measured by functional near infrared spectroscopy during  a verbal fluency task in patients with major depression and borderline personality  disorder. Diagnostic and  predictive applications of functional near infrared spectroscopy for major  depressive disorder  a systematic review." />
    </node>
    <node TEXT="healthcare">
      <node TEXT="These negative psychologi   cal feelings are associated with experiencing depression  anxiety  and  stress which can trigger mental disorders considering  31 32 . In another survey study  a preponderance of  depression  stress  and anxiety among the women was reported 28 . A different study conducted on healthcare  practitioners revealed no differences between male and female doctors  in the scores  39 . The present findings reported that stress  anxiety  and depression are  higher among younger people  18 30 years old . Similarly  a study  showed that individuals aged 40 years have higher stress levels  compared to those below the age of 40  39 . Holmes et al.  18   showed that older adults and those with low incomes  are susceptible to poor mental health. The cost of  implementing CBT can be significantly reduced using open source  learning platforms such Moodle  43 ." />
    </node>
  </node>
</map>
