<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="machine learning">
      <node TEXT="To select an approach which achieves the best results in terms of gesture classification  multiple algorithms are compared under specified categories. Between sessions  the glove is taken off and put back on in differing environmental conditions  at different ambient temperatures  for example . Suitable data partitioning is an important aspect when training machine learning algorithms since it assists with avoiding overfitting and plays a large role in determining how effective the resultant models are." />
      <node TEXT="Contents lists available at ScienceDirect Informatics in Medicine Unlocked journal homepage  www.elsevier.com locate imu Design and construction of a cost effective  portable sign language to speech translator Muhammed Rashaad Cassim  Jason Parry   Adam Pantanowitz  David M. Rubin Biomedical Engineering Research Group  School of Electrical and Information Engineering  University of the Witwatersrand  Johannesburg Private Bag 3  2050  Johannesburg  South Africa A R T I C L E I N F O Keywords  American Sign Language Gesture detection Gesture classification Machine learningA B S T R A C T This paper presents the design and construction of a cost effective  portable sign language to speech translator. Gesture classification is achieved through a supervised machine learning approach   five different algorithms are compared to determine the best configuration for this system. There are many variants of sign language  which can be broadly characterised as either fingerspelling or signed languages   2 ." />
      <node TEXT="7  Fernandez Delgado M  Cernadas E  Barro S. Do we need hundreds of classifiers to solve real world classification problems  J Mach Learn Res 2014 15 1  3133 81. 15  Paredes Madrid L  Matute A  Bareno J  Parra Vargas C  Gutierrez Velasquez E. Underlying physics of conductive polymer composites and force sensing re  sistors  FSRs . 19  Pedregosa F  Varoquaux G  Gramfort A  Michel V  Thirion B  Grisel O  et al. Scikit learn  Machine learning in python." />
      <node TEXT="9 assumes that labour costs may be neglected when calculating the system s overall cost. All algorithms performed fairly strongly in the cross validation ac  curacy category  as expected  due to this test being carried out on a single training dataset using an established machine learning library. The neural network may have achieved an even higher practical repeatability if a better hidden layer structure had been discovered." />
    </node>
    <node TEXT="supervised">
      <node TEXT="Contents lists available at ScienceDirect Informatics in Medicine Unlocked journal homepage  www.elsevier.com locate imu Design and construction of a cost effective  portable sign language to speech translator Muhammed Rashaad Cassim  Jason Parry   Adam Pantanowitz  David M. Rubin Biomedical Engineering Research Group  School of Electrical and Information Engineering  University of the Witwatersrand  Johannesburg Private Bag 3  2050  Johannesburg  South Africa A R T I C L E I N F O Keywords  American Sign Language Gesture detection Gesture classification Machine learningA B S T R A C T This paper presents the design and construction of a cost effective  portable sign language to speech translator. Gesture classification is achieved through a supervised machine learning approach   five different algorithms are compared to determine the best configuration for this system. There are many variants of sign language  which can be broadly characterised as either fingerspelling or signed languages   2 ." />
    </node>
    <node TEXT="model">
      <node TEXT="To select an approach which achieves the best results in terms of gesture classification  multiple algorithms are compared under specified categories. Between sessions  the glove is taken off and put back on in differing environmental conditions  at different ambient temperatures  for example . Suitable data partitioning is an important aspect when training machine learning algorithms since it assists with avoiding overfitting and plays a large role in determining how effective the resultant models are." />
      <node TEXT="One alternative design path to make the system adaptable is an Internet of Things approach where the microcontroller offloads new gesture data to a server for training and receives an updated model back. Finally  the project meets its goal of cost effectiveness when taking only the component cost  exclusive of labour and other associated costs  into account   the final glove is far cheaper than an alternative using store bought sensors or an alternative means of gesture sensing such as electromyographical sensors or a camera based system. This causes a clear bias in the dataset which may result in inaccurate classifi  cation of gestures when used by other people  specifically  people with a different physical hand structure to the creators ." />
    </node>
  </node>
</map>
