<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="health">
      <node TEXT="In this  respect  a personal health record  PHR  is one of the most important self care tools  which provides access to self   care services as well as chronic disease management  CDM  through monitoring and learning. The NKF  s Kidney Disease Outcomes Quality Initiative  KDOQI   guidelines accordingly divide patients with CKD based on low stability  in the estimated glomerular filtration rate  eGFR  into five stages  5     Corresponding author. Contents lists available at ScienceDirect  Informatics in Medicine Unlocked  u   zkw  s yo kr o     1ow  o to 1m y2w m k o2ty   https   doi.org 10.1016 j.imu.2022.100930  Received 8 January 2022  Received in revised form 17 March 2022  Accepted 22 March 2022" />
      <node TEXT="43  Zhou YY  Kanter MH  Wang JJ  Garrido T. Improved quality at Kaiser Permanente  through e mail between physicians and patients. 62  Djamali A  Samaniego M  Muth B  Muehrer R  Hofmann RM  Pirsch J  et al. Medical  care of kidney transplant recipients after the first posttransplant year. 92  Azizi A  Aboutorabi R  Mazloum Khorasani Z  Afzal Aghaea M  Tabesh H  Tara M.  Evaluating the effect of web based Iranian diabetic personal health record app on  self care status and clinical indicators  randomized controlled trial." />
      <node TEXT="As a result  these findings were investigated to  provide some recommendations for the app redesign. The KTPHR was a mobile based app to help KTPs manage their  health information and self care. General characteristics Value Frequency  Clinical specialty Nephrology 1  Internal medicine 2  Laboratory sciences 2  Pathology 1  Basic science specialty Medical informatics 7  Health information management 12  Gender Female 7  Male 17  Age range  years  25 35 5  35 45 11  F45 8  Work experience  years  D10 10  10 20 8  F20 6  Table 5  Details related to data classes  number of data items  and number of items  selected based on CVR." />
      <node TEXT="It should be  noted that no time limits were considered to include all articles on  KTPHR. The information item was  thus effective in identifying some items such as BUN  Cr  etc. KTPHR evaluation by usability heuristics  In this type of evaluation  the app was provided to 20 evaluators   including nephrologists  one person   health informatics and health in  formation management specialists  17 cases   and laboratory specialists   two individuals    2." />
      <node TEXT="Studies have further shown that patients suffering from kidney dis  ease are facing numerous challenges in terms of self care  including  complex decision making  frequent hospitalizations  27   the manage   ment of blood pressure  weight  total cholesterol  and blood sugar  fluid  intake  diet changes  drug compliance  and physical activities. A PHR lays emphasis on patient empowerment and better patient   doctor interaction to improve health care quality as a reliable proced   ure to implement an electronic health record  EHR   which can boost  clinical decision making along with comprehensive data collection  38 . With regard to upgrading paper based PHR into electronic ones   there is a consensus that the digitization of health records can help retain  information over time  and such information consequently leads to  improved availability of health services and their consequences  46 ." />
    </node>
    <node TEXT="model">
      <node TEXT="The study results suggested a model for KTPHR tools to involve pa  tients in their self care process. Topics  such as digital divide  computer literacy  age  and interest in Table 12  Results of qualitative heuristic usability evaluation. 5 It is better to consider the borderline or suspicious values for tests with positive  and negative results  such as BKV." />
    </node>
  </node>
</map>
