<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="health">
      <node TEXT="Informatics in Medicine Unlocked 30  2022  100942 4gynecological symptoms obtained from the internet is evaluated by  patients and which interindividual determinants may influence this. It could be shown that internet capable devices were  available in 91   but less frequently with increasing age and decreasing  schooling. Characteristics Patients n  1271  100    Do you have an internet enabled device   Smartphone  Tablet  Computer     Yes 1.162  91.4    No 109  8.6    Which device do you prefer to go online   Smartphone 644  55.4    Tablet 270  23.2    PC Laptop 198  17.1    Other 50  4.3    I feel able to use internet enabled devices  n      Strongly disagree 66  5.2    Disagree 35  2.8    Neutral 285  22.4    Agree 652  51.3    Strongly agree 233  18.3    Do you use internet enabled devices more regularly since the COVID 19 pandemic   n       Yes 1.051  82.7    No 220  17.3    Has your attitude towards internet enabled devices changed due to the COVID 19  pandemic   n      It changed positively 596  46.9   It changed negatively 238  18.7   It has been unaffected 437  34.4   How often do you use internet enabled devices since the COVID 19 pandemic   Several time a day 873  68.7    Once a day 215  16.9    Once weekly 101  7.9    Never use 82  6.5    Table 2  Usage of digital health applications before and after COVID 19 pandemic  n    ." />
      <node TEXT="This is an open access article under the CC BY NC ND license   http   creativecommons.org licenses by  nc nd 4.0   .E health   The importance of the internet as an informative digital health  application for gynecological patients in times of SARs CoV2  A national  cross sectional survey  Stefan Hertlinga b c    Doreen Hertlingd  Ekkehard Schleu  nera  Franziska Loose   Isabel Graulb f g  aDepartment of Obstetrics  University Hospital Jena  Jena  Germany  bOrthopaedic Department  Campus Eisenberg  University Hospital Jena  Eisenberg  Germany  cFakult  at f r Gesundheit  Department f r Humanmedizin   Lehrstuhl f r Medizintheorie  Integrative und Anthroposophische Medizin  Witten  Herdecke  Germany  dHospital Rummelsberg  Schwarzenbruck  Germany  ePractice for Orthopaedics and Shoulder Surgery  Leipzig  Germany  fDepartment of Trauma  Hand and Reconstructive Surgery  University Hospital Jena  Jena  Germany  gDepartment f r Orthop  adie  Unfall   Universit  atsklinikum Halle  Halle  Germany    ARTICLE INFO   Keywords   eHealth  Gynecology  Myoma  Endometriosis  Internet ABSTRACT   Introduction  The internet plays an important role as a digital source of information. In addition  more than 82   n  1046  believe that the use of digital health  applications can have a positive impact on their disease treatment. The internet was seen as a helpful health information platform in addition to medical  consultation." />
      <node TEXT="Almost  20  of respondents  n  248  prefer a PC or laptop and other internet   enabled devices. Only 6    n  82  said they had never used internet enabled devices since the  COVID 19 pandemic  Table 1 . In addition  it  was investigated how trustworthy the health information on  Fig." />
      <node TEXT="The Internet often serves as an  informative digital health application because a source of medical in  formation is essential. But it accelerated this devel   opment and is also reflected in the healthcare sector  12 . Members of the  Working Group Young Gynecology and Obstetrics  Arbeitsgemeinschaft  Junges Forum der Deutschen Gesellschaft f r Gyn akologie und  Geburtshilfe  DGGG  were invited for the validation process to provide  feedback on question format  comprehensiveness  clarity  and flow  15 ." />
      <node TEXT="However  other studies show  that older people are increasingly using the internet as a health infor  mation medium. In our study  more than two thirds of patients search the internet  for health information about their gynecological symptoms before  visiting a doctor. In this study  more than two thirds of patients  search the internet for health information about their gynecological  symptoms before visiting a doctor." />
    </node>
    <node TEXT="healthcare">
      <node TEXT="The Internet often serves as an  informative digital health application because a source of medical in  formation is essential. But it accelerated this devel   opment and is also reflected in the healthcare sector  12 . Members of the  Working Group Young Gynecology and Obstetrics  Arbeitsgemeinschaft  Junges Forum der Deutschen Gesellschaft f r Gyn akologie und  Geburtshilfe  DGGG  were invited for the validation process to provide  feedback on question format  comprehensiveness  clarity  and flow  15 ." />
    </node>
  </node>
</map>
