<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="health">
      <node TEXT="Significant differences between male and female par  ticipants were identified with respect to E Health literacy as shown in  Table 3. Therefore  significant differences in the E Health literacy  between males and females can be observed. Significant differences between the participants were iden  tified with respect to E Health literacy levels as shown in Table 4." />
      <node TEXT="Methods  A questionnaire based  E Heals  survey was adopted for collecting the data from students. In  addition  future studies should focus on the influencing factors of E Health literacy across various population  samples. Young population  15 24 years  were identified to be  effective users of internet services  spending more than 5 h daily on an  average  4 5   who mainly belong to secondary and tertiary levels in the education  who were also being taught using E Learning approaches  6 ." />
      <node TEXT="Significant differences between the participants  were identified with respect to E Health literacy levels as shown in  Table 5. Thus  this study has identified that E Health  literacy among secondary school students in Saudi Arabia was identified  to varying between medium and high levels  with few discrepancies  among genders and type of schools. How  ever  a mixed method approach  where by adding qualitative ap  proaches such as interviews could have gathered more qualitative and  behavioral data which can be used to analyze the literacy levels in more  detail along with various variables or factors of influence." />
      <node TEXT="Questionnaire design  eHealth Literacy Scale  eHEALS   a self report tool that can be  administered by a health professional and is based on an individual  s  perception of her or his own skills and knowledge within each measured  domain was used in the survey  12 . Medium and large schools  as categorized by  the Department of Education  were considered to ensure maximum  variation. Results  The participants E Health literacy levels reflected above average  skills with respect to various activities as shown in Table 2." />
      <node TEXT="How the public uses social media wechat to obtain  health information in China  a survey study. Factors influencing eHealth literacy of middle school students in Korea  a  descriptive cross sectional study. Association of eHealth literacy with lifestyle behaviors in university  students  questionnaire based cross sectional study." />
    </node>
  </node>
</map>
