<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="health">
      <node TEXT="1.DEGs in expression microarrays of four datasets of bipolar and healthy controls with cutoff  P value D0.01  logFC F0.5 and common DEGs between four  mentioned expression arrays. E  Venn  diagram of upregulated genes. F  Venn diagram of downregulated genes." />
      <node TEXT="Receiver operating characteristic  ROC  curve and area under the curve  AUC  statistics  are used to evaluate the capacity to discriminate BD from healthy controls with excellent specificity and sensitivity. Bar diagram shows fold change in expression of  core miRNAs. Statistical comparisons were made with respective 5 s rRNA  P D0.05 for all miRNAs." />
      <node TEXT="Several studies have  reported aberrant expression of miR 19b 3p associated with other  brain derived disorders  29 32  Additionally  the study done by Lee  et al. determined over expression of miR 23b 3p in bipolar patients  compared with healthy individuals  33 . Based on experiments  patients with BD had a more increased level  of Uric Acid  particularly in mania seizures. Our findings  imply that these two miRNAs may be biomarker candidates for BD." />
      <node TEXT="This is an open access article under the CC BY NC ND license   http   creativecommons.org licenses by nc nd 4.0   .Hsa miR 19b 3p and Hsa miR 23b 3P are the candidate biomarkers for  bipolar disorder  Omran Davarinejada  Zahra Foruzandehb  Payam Mohammadia  Farzaneh Golmohammadia   Davood Ghavib  MohammadReza Alivandb  Misagh Chogana  Hossein Zhalehc   Yazdan Rahmatia    aClinical Research Development Center  Imam Khomeini and Mohammad Kermanshahi and Farabi Hospitals  Kermanshah University of Medical Sciences  Kermanshah   Iran  bDepartment of Medical Genetics  Faculty of Medicine  Tabriz University of Medical Sciences  Tabriz  Iran  cSubstance Abuse Prevention Research Center  Health Institute  Kermanshah University of Medical Sciences  Kermanshah  Iran    ARTICLE INFO   Keywords   Bipolar disease  microRNA  Biomarker  Real time PCR ABSTRACT   Bipolar disorder  BD  is a severe psychiatric disorder and among the leading causes of disability worldwide that  has a significant genetic component with high heritability. Furthermore  RT qPCR on 50 BD samples and 50 healthy controls was performed to  validate the in silico results. 1.Introduction  Non coding RNAs comprise a large proportion of human tran  scriptome mainly with no known encoded protein  however  they have  been found to play essential roles in regulation of cellular functions such  as cell cycle and proliferation  1 ." />
      <node TEXT="Investigations on the blood  and post mortem brains of people with this disorder have found aberrant  gene expression  28 . Numerous miRNAs showed the ability to significantly differ   entiate between patients with BD and healthy  normal ones. 3.Dysregulated signaling pathways and interacted genes  nodes with red mark  after functional enrichment analysis using ClueGO  a Cytoscape plug in." />
    </node>
  </node>
</map>
