<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="model">
      <node TEXT="2B D depict the distinct transcriptional signature  caused by AD and HD. Additionally   ontology and annotation are designed to facilitate the execution of a  complicated biological structure model  which is often employed in  biomedical activities  37 . 3 A C  displays the overall ontology assessment for each group. The  main significant ontology was cellular response to interferon gamma   interferon gamma mediated signaling pathway  positive regulation of  leukocyte cell cell adhesion  T cell receptor signaling pathway  inter  leukin 17 receptor activity  chitinase activity  MHC class II receptor  activity  MHC protein complex  integral component of lumenal side of  endoplasmic reticulum membrane  COPII coated ER to Golgi transport  vesicle  MHC class II protein complex etc. It acts as a model technique for demonstrating  how different diseases interact through fundamental molecular or bio  logical processes  38 . Four worldwide databases  KEGG  WikiPath   ways  Reactome  and BioCarta  were used to extract the most affected  pathways of common DEGs between AD and HD. The network is made up of 24 nodes and  159 edges." />
    </node>
    <node TEXT="supervised">
      <node TEXT="Md Habibur Rahman and Mohammad Ali Moni supervised the  whole project. Declaration of competing interest  The authors declare that they have no known competing financial  interests or personal relationships that could have appeared to influence  the work reported in this paper. Habibur Rahman who helped us and provided  valuable insight into the research. 3 Rahman MH  Rana HK  Peng S  Kibria MG  Islam MZ  Mahmud SH  Moni MA. 12  Moss DJH  Flower MD  Lo KK  Miller JR  van Ommen G JB  AC t Hoen P  Stone TC   Guinee A  Langbehn DR  Jones L  et al. Huntington  s disease blood and brain show  a common gene expression pattern and share an immune signature with  alzheimer  s disease. 14  Udhaya Kumar S  Thirumal Kumar D  Siva R  George Priya Doss C  Younes S   Younes N  Sidenna M  Zayed H. Dysregulation of signaling pathways due to  differentially expressed genes from the b cell transcriptomes of systemic lupus  erythematosus patients  a bioinformatics approach. 10.The network of gene disease associations depicts common DEG related diseases." />
    </node>
    <node TEXT="machine learning">
      <node TEXT="19  Scheckel C  Drapeau E  Frias MA  Park CY  Fak J  Zucker Scharff I  Kou Y   Haroutunian V  Ma ayan A  Buxbaum JD  et al. Regulatory consequences of  neuronal elav like protein binding to coding and non coding rnas in human brain. A cross platform comparison of affymetrix  agilent  and  illumina microarray reveals functional genomics in colorectal cancer progression. A network based bioinformatics approachto identify molecular biomarkers for type  2 diabetes that are linked to the progression of neurological diseases. Bioinformatics  and machine learning methodologies to identify the effects of central nervous  system disorders on glioblastoma progression. Single nucleus transcriptome analysis reveals  dysregulation of angiogenic endothelial cells and neuroprotective glia in  alzheimer  s disease. 51  Kawalia SB  Raschka T  Naz M  de Matos Simoes R  Senger P  Hofmann Apitius M.  Analytical strategy to prioritize alzheimer  s disease candidate genes in gene  regulatory networks using public expression data. 52  Jiang Q  Hu Y  Liu G. Association of alzheimer disease susceptibility variants and  gene expression in the human brain." />
    </node>
  </node>
</map>
