<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="health">
      <node TEXT="This is an open access article under the CC BY license   http   creativecommons.org licenses by 4.0   .IRlab   Platform for thermal video analysis in evaluation of peripheral  thermal behavior and blood perfusion  Tomppa Pakarinena    Niku Oksalaa b  Antti Vehkaojaa  aFaculty of Medicine and Health Technology  Tampere University  Tampere  Finland  bVascular Surgery and Procedural Radiology  Tampere University Hospital  Tampere  Finland    ARTICLE INFO   Keywords   Thermal imaging  Angiosome  Peripheral blood flow  Perfusion  Matlab ABSTRACT   Background and objectives  Dynamic thermal imaging in medicine has several advantages in comparison to static  thermal image analysis and has potential as a novel patient assessment method e.g. in the area of vascular  surgery. Conclusions  IRlab is a versatile tool for dynamic thermal image and video processing. Freeware and open source  programs for medical thermal imaging are severely lacking  thus as a completely open source project IRlab offers  a unique platform for researchers within the field of medical thermal imaging. In the United States alone  there are over 12 million patients suffering from PAD  4 . The current clinical PAD diagnostic methods include physio   logical measurements  such as ankle brachial index  toe brachial index  transcutaneous oximetry  TcSPO2   toe systolic pressure and skin  perfusion pressure. All of these methods require patient contact and do  not offer spatial information apart from a single measurement point. Contents lists available at ScienceDirect  Informatics in Medicine Unlocked  u   zkw  s yo kr o     1ow  o to 1m y2w m k o2ty   https   doi.org 10.1016 j.imu.2022.100940  Received 30 December 2021  Received in revised form 28 March 2022  Accepted 1 April 2022" />
      <node TEXT="The polygon vertices are used to  compute binary masks for each delineated ROI. In case of imperfect registration or asymmetrical  anatomy  both ROIs may be modified interactively after initial drawing. There is no limit for the total number of ROIs. Thermo modulation analysis  Dynamic thermal modulation tool analyses thermal recovery  caused  by active cooling or possibly the effects of active heating of an  anatomical location. We hypothesize that normal  unrestricted  and healthy  perfusion to a single artery sourced angiosome  29  follows during  thermal recovery  with a time constant proportional to the vasculari   zation and perfusion of the area. Perfusion in angiosomes covered with  several source arteries could possibly be modeled as the superposition of  the source arteries proportional contribution. Artefact removal  IRlab includes an artefact removal tool  30  for computed 1D tem  perature curves  which can be used in three types of artefacts from the  extracted median curves for each ROI." />
    </node>
    <node TEXT="model">
      <node TEXT="The polygon vertices are used to  compute binary masks for each delineated ROI. In case of imperfect registration or asymmetrical  anatomy  both ROIs may be modified interactively after initial drawing. There is no limit for the total number of ROIs. Thermo modulation analysis  Dynamic thermal modulation tool analyses thermal recovery  caused  by active cooling or possibly the effects of active heating of an  anatomical location. We hypothesize that normal  unrestricted  and healthy  perfusion to a single artery sourced angiosome  29  follows during  thermal recovery  with a time constant proportional to the vasculari   zation and perfusion of the area. Perfusion in angiosomes covered with  several source arteries could possibly be modeled as the superposition of  the source arteries proportional contribution. Artefact removal  IRlab includes an artefact removal tool  30  for computed 1D tem  perature curves  which can be used in three types of artefacts from the  extracted median curves for each ROI." />
      <node TEXT="4 Gerhard Herman M  et al. 2016 AHA ACC guideline on the management of  patients with lower extremity peripheral artery disease. 7 Rother U  Lang W  Horch RE  Ludolph I  Meyer A  Gefeller O  Regus S. Pilot  assessment of the angiosome concept by intra operative fluorescence angiography  after tibial bypass surgery. 10  Sumpio B  Forsythe R  Ziegler K  van Baal J  Lepantalo M  Hinchliffe R. Clinical  implications of the angiosome model in peripheral vascular disease. 13  Geyer M  Yih Kuen J  Brienza D  Boninger M. Using wavelet analysis to  characterize the thermoregulatory mechanisms of sacral skin blood flow. In  Influence of temporal noise on the skin  blood flow measurements performed by cooled thermal imaging camera  limit  possibilities within each physiological frequency range   Proc. 19  Gonz  alez P  erez S  Perea Str om D  Arteaga Marrero N  Luque C  Sidrach Cardona I   Villa E  Ruiz Alzola J. 30  Pakarinen T  Pietil  a J  Nieminen H. Prediction of self perceived stress and arousal  based on electrodermal activity  ." />
    </node>
  </node>
</map>
