<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="machine learning">
      <node TEXT="Recent progress in machine learning based NLP has shown great  potential towards automating the classification process of free radiology  text. Methodological contributions    a  This study investigated the use of three traditional machine  learning algorithms  support vector machine SVM  logistic  regression LR and random forest RF  as well as two deep learning  algorithms  convolutional neural networks CNNs and recurrence  neural network RNN with bi directional long short term memory  Bi LSTM  for auto assigning the appropriateness of LSMRI re  ferrals. Dataset  This study was approved by the institutional review board of Uni  versity College Dublin UCD." />
      <node TEXT="SVMs were optimized  with the radial basis function kernel  RBF   a regularization value of C   5  and gramma  0.1. Bi LSTM DA did show higher accuracy and F1 score than other  models. 4.AUC ROC and confusion matrix of the best machine learning models with data augmentation." />
      <node TEXT="The researchers intended  to keep the held out subset quite challenging with imbalance distribu   tion as there are only 22 not indicated referrals vs 78 indicated. Traditional machine learning models  Random forest model with TF IDF  RF TF IDF  achieved the highest  performance among models trained and tested on the original subset  with AUC of 0.813 and F1 of 0.917. Random forest was optimized with  Table 1  Training and testing results of all developed models using the original and augmented subsets." />
    </node>
    <node TEXT="model">
      <node TEXT="SVMs were optimized  with the radial basis function kernel  RBF   a regularization value of C   5  and gramma  0.1. Bi LSTM DA did show higher accuracy and F1 score than other  models. 4.AUC ROC and confusion matrix of the best machine learning models with data augmentation." />
      <node TEXT="These findings indicate that the applications of machine  learning and deep learning based NLP in referral texts could improve the  management of referrals in radiology departments. The fundamental issue with training a model on imbalanced data is  Fig. 5.AUC ROC and confusion matrix of the best deep learning models with data augmentation." />
      <node TEXT="The researchers intended  to keep the held out subset quite challenging with imbalance distribu   tion as there are only 22 not indicated referrals vs 78 indicated. Traditional machine learning models  Random forest model with TF IDF  RF TF IDF  achieved the highest  performance among models trained and tested on the original subset  with AUC of 0.813 and F1 of 0.917. Random forest was optimized with  Table 1  Training and testing results of all developed models using the original and augmented subsets." />
      <node TEXT="The models were compiled using Adam optimizer  with learning rate  2e 2  and binary cross entropy loss function. Manual optimization was performed for both models using batch size   180  epochs  30  and 0.5 dropout after each layer. 3.A diagram showing the pipeline for data pre processing  models   development  and final comparison." />
      <node TEXT="Bag of words features extraction techniques with SVM slightly out  performed TF IDF in the augmented subsets. However  in their study  a larger  dataset comprising 2500 reports was used for training  whereas in this  study  the training set  after augmentation  included 1061 referrals  and  as it is known that deep neural models tend to require more data to show  good performance  25 . SVM BoW DA demonstrated the second highest performance  with accuracy  0.84  F1  0.90 and correct classification of 12 not  indicated referrals." />
      <node TEXT="Third  the comparison  between models and radiologists was conducted on a small held out  subset  only 100 referrals. Fourth  this study did not investigate using more complex architectures such as  attention based RNN and multi channel CNN  which might solve the  issue of timing codes ignorance reported in the error analysis. 5.Conclusion  This study reports the results of several traditional and deep learning  models developed using two data subsets  original and augmented  with  different features extraction techniques for auto auditing the appropri   ateness of LSMRI referrals." />
      <node TEXT="This was followed by a  single CNN layer with 50 neurons  3 3 convolutions  and Relu activation  in both models. A fully  connected layer with 50 neurons and Relu activation was placed after  the global maximum pooling to flatten its output in both models. Both models were compiled using  adaptive moment estimation optimizer  Adam  with learning rate  2e   2  and binary cross entropy loss function." />
    </node>
  </node>
</map>
