<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="model">
      <node TEXT="Also  these algorithms have been applied for many prediction pur  poses in the medical field such as breast cancer  diabetes  and other  diseases. The propsed models in this work were implemented using Python  programming language which provides several tools for machine  learning tasks. The trees protect each  other from their flaws  which explains why they have such a strong ef  fect." />
      <node TEXT="For all developed models  feature selection did not contribute to  improving performance. The obtained correlation results show that age  C Reactive  Protein  nasal oxygen support days  organ dysfunction or failure  LDH   blood oxygen saturation  headache  autoimmune disease  D dimer  and  ferritin are the features that can strongly indicate the need for patients to  be in ICU. Four prediction  models were developed using ML classifiers  RF  GB  XGBoost  and  Ensemble as those four classifiers are known to perform well for the  targeted purpose." />
      <node TEXT="To solve this imbalanced dataset issue  Syn  thetic Minority Oversampling Technique  SMOTE  was used. Up sampling of similar data  does not show any impact in  improving results  42 . Extreme  Gradient  Boosting   XGBoost    Designed to be used with  large complex datasets and  avoid model overfitting." />
      <node TEXT="The selected classifiers are Random Forest RF  Gradient Table 1  Summary of works aimed at estimating the need and LoS in ICU for COVID 19 patients worldwide. Ref Aim Model Algorithms   Methods Dataset Model inputs Extracted  features Results   10  Predict ICU admission  LoS in  the ICU  and mortality for  COVID 19 patients Multivariate logistic  regression LR EHRs of 1668 COVID 19 patients at  Merkezefendi State Hospital   Manisa   Turkey   Clinical data AUC  0.89   19  Predict patient census and  estimate ventilator needs for  a specific hospital during the  COVID 19 pandemic Analytical model   Weibull  distribution  Linear and log   linear regression EHRs from UHT and UIHC of COVID   19 patients LoS in hospital  and  duration of using the  ventilator MAE  D1.25  patients day  D0.5  ventilators day   20  Estimate LoS of hospitalized  COVID 19 patients Non parametric  model   EHRs of 10 454 confirmed COVID   19 cases in Galicia  Northwest  Spain   Age  and gender     21  Estimate the LoS of COVID 19  patients in ICU Semiparametric  distributional index  model Distributional  regression model EHRs of 2411 patients with ARDS for  training  and EHRs of 557 COVID 19  patients for testing  the data from the  Swiss Society of Intensive Care  Medicine Age  and gender Accuracy predict  patient discharged  from the ICU in 20  days  80    24  Describe COVID 19 clinical  characteristics outside of  Wuhan and predict the risk of  long LoS in hospital Multivariate  regression model Statistical  methods  t test   Chi square  EHRs of 75 COVID 19 patients in  Zhejiang Tertiary Care Hospital Demographic data   comorbidities   laboratory results  symptoms  and vital  signs AUC  0.84   23  Predict ICU admission  LoS in  the ICU  and mortality for  COVID 19 patients ML model SVM EHRs of 733 COVID 19 patients in  Wuhan  China Demographic   laboratory  and clinical  data Accuracy of   1. Factor Studies that confirmed  relation Studies that confirmed  no relation  Age  10 20 23   19 24   Gender  20 21   19 24   Weight   24   Career   24   Heart disease  10 23     Hypertension  10     Diabetes mellitus  10     Stroke  10     Vascular disease  10     Lymphocyte absolute  value  23     Erythrocyte count  23     Total cholesterol  23     Adenovirus IgM antibody  23     Hypersensitive C  reactive  protein  23     High sensitivity troponin I  23     Q fever Rickettsia IgM  antibody  23     D.A." />
      <node TEXT="Allocating the Intensive Care  Unit  ICU  beds   capacity is important since COVID 19 is a respiratory disease and some patients need to be  admitted to the hospital with an urgent need for oxygen support  ventilation  and or intensive medical care. Four ML algorithms were utilized  Random Forest  RF   Gradient Boosting  GB   Extreme Gradient Boosting   XGBoost   and Ensemble models were trained and validated on a dataset of 895 COVID 19 patients admitted to  King Fahad University hospital in the eastern province of Saudi Arabia. Although these measures play a significant role in managing medical  resources  they  in turn  may put the lives of COVID 19 patients at risk   as happened in the United Kingdom when several patients adhered to  home quarantine  which led to their death  and their condition was not  discovered for a period up to two weeks  6 ." />
      <node TEXT="The obtained results with this model are shown in Table 11  which achieved 93.13  accuracy without feature selection. For this purpose  four  prediction models were implemented using different ML classifiers with  multiple tuning of the parameters. Attribute Entropy Evaluation  Gender 0.64  Age 4.03  DM 0.71  HTN 0.68  Cardiac 0.40  Obesity 0.31  Smoking 0.2  Vitamin D def  0.04  Renal 0.23  Liver disease 0.12  Autoimmune disease 0.10  Fever 0.71  Dry Cough 0.71  Fatigue 0.45  Headache 0.35  Dyspnea 0.64  Flu Symptoms 0.36  diarrhea 0.53  RR 2.86  Blood oxygen saturation  SATS  3.28  Mode of infection 0.80  1st sample 0.08  Chloroquine  Hydroxychloroquine 0.72  Azithromycin  Antibiotics 0.43  Steroids 0.63  Tocilizumab 0.56  Respiratory failure 0.17  Acute renal failure 0.10  Acute coronary syndrome 0.06  ARDS 0.06  GI complication 0.03  Nosocomial infection 0.03  Septic shock 0.06  Organ dysfunction or failure 0.13  lymph 5.35  Neut 5.56  LDH 5.64  ALT 4.34  AST 4.57  Trop 4.73  ferritin 5.93  D dimer 5.47  CRP 5.90   Table 5  The results of predicting the number of days to discharge from ICU class for  Model 1." />
      <node TEXT="3 Bravata DM  Perkins AJ  Myers LJ  Arling G  Zhang Y  Zillich AJ  Reese L   Dysangco A  Agarwal R  Myers J  Austin C  Sexson A  Leonard SJ  Dev S  Keyhani S.  Association of intensive care unit patient load and demand with mortality rates in  US department of Veterans Affairs hospitals during the COVID 19 pandemic. Machine learning approach to  predicting COVID 19 disease severity based on clinical blood test data  statistical  analysis and model development. A risk prediction model for type 2 diabetes based on weighted  feature selection of random forest and XGBoost ensemble classifier  2019 elev." />
    </node>
    <node TEXT="machine learning">
      <node TEXT="Informatics in Medicine Unlocked 30  2022  100937 10 40  Uddin S  Khan A  Hossain ME  Moni MA. 41  Pan Y  Liu D  Deng L. Accurate prediction of functional effects for variants by  combining gradient tree boosting with optimal neighborhood properties. 43  Smitha N  Bharath R. Performance comparison of machine learning classifiers for  fake news detection." />
      <node TEXT="For such purposes  Artificial Intelligence  AI   namely Machine Learning   ML   has made a significant contribution during the COVID 19  pandemic  7 . Izquierdo et al. found that the  most common clinical characteristics determining admission to ICU  were fever  age  and tachypnea with without respiratory crackles  17 . They  found also that age  weight  gender  and career are not affecting the  length of hospital stay." />
      <node TEXT="3 Bravata DM  Perkins AJ  Myers LJ  Arling G  Zhang Y  Zillich AJ  Reese L   Dysangco A  Agarwal R  Myers J  Austin C  Sexson A  Leonard SJ  Dev S  Keyhani S.  Association of intensive care unit patient load and demand with mortality rates in  US department of Veterans Affairs hospitals during the COVID 19 pandemic. Machine learning approach to  predicting COVID 19 disease severity based on clinical blood test data  statistical  analysis and model development. A risk prediction model for type 2 diabetes based on weighted  feature selection of random forest and XGBoost ensemble classifier  2019 elev." />
    </node>
  </node>
</map>
