<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="model">
      <node TEXT="This is an open access article under the CC BY NC ND license   http   creativecommons.org licenses by  nc nd 4.0   .Potential senotherapeutic candidates and their combinations derived from  transcriptional connectivity and network measures  Amirhossein Nayeri Rada 1  Golnaz Shamsa 1  Roberto A. Avelarb  Mohammad  Hossein Morowvata    Younes Ghasemia c  aPharmaceutical Sciences Research Center  Shiraz University of Medical Sciences  P.O. Various attempts have been made to find a unified gene signature for all senescence models in every cell  type. However  with more studies being conducted  none look to be universally shared  instead  it seems that the  senescence gene signature is cell type specific. Cellular senescence was first described  by Hayflick and Moorhead as a process that limited human cell prolif   eration following prolonged cultivation in culture  2 . It is now  described as a process of permanent growth arrest in response to various  stressors. These conditions are regulated by networks of multiple  cellular pathways which have not been clearly identified yet. However  the identification of effective drug combinations is mostly  an experimentally long process with a high failure rate." />
    </node>
    <node TEXT="health">
      <node TEXT="37  Hernandez Segura A  de Jong TV  Melov S  Guryev V  Campisi J  Demaria M.  Unmasking transcriptional heterogeneity in senescent cells. 49  Hulsen T  de Vlieg J  Alkema W. BioVenn   a web application for the comparison  and visualization of biological lists using area proportional Venn diagrams. 54  Yu S  Lee E  Tsogbadrakh B  Son G I  Kim M. Prenatal hyperbaric normoxia  treatment improves healthspan and regulates chitin metabolic genes in Drosophila  melanogaster. 55  Takemon Y  Chick JM  Gerdes Gyuricza I  Skelly DA  Devuyst O  Gygi SP   Churchill GA  Korstanje R. Proteomic and transcriptomic profiling reveal different  aspects of aging in the kidney. 56  Ciccarone F  Tagliatesta S  Caiafa P  Zampieri M. DNA methylation dynamics in  aging  how far are we from understanding the mechanisms  Mech Ageing Dev  2018 174 3  17. Identification of CD44 as a senescence induced cell adhesion gene  responsible for the enhanced monocyte recruitment to senescent endothelial cells. 69  Tang X  Milyavsky M  Goldfinger N  Rotter V. Amyloid    precursor like protein  APLP1 is a novel p53 transcriptional target gene that augments neuroblastoma cell  death upon genotoxic stress." />
    </node>
  </node>
</map>
