<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="machine learning">
      <node TEXT="32  Drewett GP  Chan RK  Jones N  Wimaleswaran H  Howard ME  McDonald CF  et al.  Risk factors for readmission following inpatient management of COVID 19 in a  low prevalence setting. 39  Shin S  Austin PC  Ross HJ  Abdel Qadir H  Freitas C  Tomlinson G  et al. Machine  learning vs. conventional statistical models for predicting heart failure readmission  and mortality. 45  Min X  Yu B  Wang F. Predictive modeling of the hospital readmission risk from  patients   claims data using machine learning  a case study on COPD." />
      <node TEXT="Material and methods  The data of 5791 hospitalized patients with COVID 19 were retrospectively recruited from  a hospital registry system. Conclusion  The experimental results prove that ML models can satisfactorily predict COVID 19 readmission. Many patients in  such conditions were discharged after admission with partial recovery  Abbreviations  COVID 19  Coronavirus disease 2019  CDSS  Clinical Decision Support Systems  ML  Machine learning  CRISP  Cross Industry Standard Process   LASSO  Least Absolute Shrinkage and Selection Operator  AUC  Area under the curve  HGB  Hist Gradient Boosting  MLP  Multi Layered Perceptron  SVM  Support  Vector Machine  XGBoost  Extreme Gradient Boosting." />
    </node>
    <node TEXT="model">
      <node TEXT="The KNN classifier with mean classification  accuracy 88.3   specificity 87.8   sensitivity 89.2   F  measure  89.37   Kappa statistic 88.3   and AUC 88.6  achieved nearly  acceptable performance. So far  most previous ML based studies have focused on predicting  readmission of chronic conditions such as cardiovascular  1 34 39    stroke  40 44   and COPD  5 6 45 47 . Koteswari  2020  proposed an intelligent model to predict the  readmission probability of various COVID 19 cases using ML techniques." />
      <node TEXT="Ac  cording to the formal reports  about 5  of COVID 19 confirmed patients  necessitate hospitalization care services  and the tolls of readmission  from this disease report vary from 2 to 10   14 15 . Recently  published works have shown that several ML methods are  more accurate than conventional statistics models for predicting clinical  outcomes in COVID 19 hospitalized patients. This study used Python programming language to run all experiments on  the data mining algorithms to predict readmission in patients with  confirmed COVID 19  see Fig." />
      <node TEXT="Table 1 indicated that there  was a significant association between some features of patients who  readmitted or not  features with p value D0.005 that showed in Table 1  with     symbol  have a significant difference in patients who read  mitted d or not class. Moreover  age and solid metastatic tumor have  a low score in relevant variables scores  so it means that age and solid  metastatic tumor have a low impact on the prediction of readmission in  confirmed COVID 19 patients. After the  preprocessing step  several ML modeling was performed by adjusting  and optimizing hyper parameters." />
      <node TEXT="32  Drewett GP  Chan RK  Jones N  Wimaleswaran H  Howard ME  McDonald CF  et al.  Risk factors for readmission following inpatient management of COVID 19 in a  low prevalence setting. 39  Shin S  Austin PC  Ross HJ  Abdel Qadir H  Freitas C  Tomlinson G  et al. Machine  learning vs. conventional statistical models for predicting heart failure readmission  and mortality. 45  Min X  Yu B  Wang F. Predictive modeling of the hospital readmission risk from  patients   claims data using machine learning  a case study on COPD." />
      <node TEXT="Material and methods  The data of 5791 hospitalized patients with COVID 19 were retrospectively recruited from  a hospital registry system. Conclusion  The experimental results prove that ML models can satisfactorily predict COVID 19 readmission. Many patients in  such conditions were discharged after admission with partial recovery  Abbreviations  COVID 19  Coronavirus disease 2019  CDSS  Clinical Decision Support Systems  ML  Machine learning  CRISP  Cross Industry Standard Process   LASSO  Least Absolute Shrinkage and Selection Operator  AUC  Area under the curve  HGB  Hist Gradient Boosting  MLP  Multi Layered Perceptron  SVM  Support  Vector Machine  XGBoost  Extreme Gradient Boosting." />
      <node TEXT="Informatics in Medicine Unlocked 30  2022  100908 32720  46.96   were women  and the median age of participants was  57.25  interquartile 00 100 . If the co  efficients value of variables is equal to zero  these zero Values for fea  tures eliminated that from features subset  and if any variables obtained  high values for coefficients. Cross validation is a resampling method used to  assess ML models in an unseen data sample." />
    </node>
  </node>
</map>
