<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="healthcare">
      <node TEXT="This is an open access article under the CC BY NC ND license   http   creativecommons.org licenses by  nc nd 4.0   .RecoMed  A knowledge aware recommender system for  hypertension medications  Maryam Sajdea  Hamed Malekb    Mehran Mohsenzadeha  aComputer Engineering Department  Science and Research Branch  Islamic Azad University  Tehran  Iran  bFaculty of Computer Science and Engineering  Shahid Beheshti University  Tehran  Iran    ARTICLE INFO   Keywords   Medicine recommender systems  Healthcare system  Hypertension  ATC code ABSTRACT   Background   Objective  High medicine diversity has always been a significant challenge for prescription  causing  confusion or doubt in physicians   decision making process. The second step entails graph mining and clustering to present an enriched  recommendation via ATC code  which itself comprises several steps. For example  in 2016  researchers developed a recommender system  that could recommend an attending physician based on the patient  s  health profile." />
    </node>
    <node TEXT="health">
      <node TEXT="Informatics in Medicine Unlocked 30  2022  100950 9 4 Kumar Singh M  Prasad Sahu D. Research aspects of the recommender system. 5 Valdez AC  Ziefle M  Verbert K  Felfernig A  Holzinger A. Recommender systems for  health informatics  state of the art and future perspectives. 16  Guo L  Jin B  Yao C  Yang H  Huang D  Wang F. Which doctor to trust  a  recommender system for identifying the right doctors." />
      <node TEXT="This is an open access article under the CC BY NC ND license   http   creativecommons.org licenses by  nc nd 4.0   .RecoMed  A knowledge aware recommender system for  hypertension medications  Maryam Sajdea  Hamed Malekb    Mehran Mohsenzadeha  aComputer Engineering Department  Science and Research Branch  Islamic Azad University  Tehran  Iran  bFaculty of Computer Science and Engineering  Shahid Beheshti University  Tehran  Iran    ARTICLE INFO   Keywords   Medicine recommender systems  Healthcare system  Hypertension  ATC code ABSTRACT   Background   Objective  High medicine diversity has always been a significant challenge for prescription  causing  confusion or doubt in physicians   decision making process. The second step entails graph mining and clustering to present an enriched  recommendation via ATC code  which itself comprises several steps. For example  in 2016  researchers developed a recommender system  that could recommend an attending physician based on the patient  s  health profile." />
    </node>
    <node TEXT="supervised">
      <node TEXT="Informatics in Medicine Unlocked 30  2022  100950 8likely to be used in real world applications as medical data are generally  unlabeled  and supervised learning models cannot be directly built using  these types of data. It is possible to recommend medicines by collecting a database of  patients   clinical symptoms resulting from clinical questionnaires  designed by the medical team  including personal information such as  age  height  weight  BMI   daily activity  patient history  underlying  diseases  and consumable medicines. Acknowledgement  We would like to thank  Behpardaz Jahan  Inc.  for helping us in  collecting the data." />
      <node TEXT="Informatics in Medicine Unlocked 30  2022  100950 7 WHO  can provide high quality and acceptable results to prescribe  blood pressure drugs which are usually used together. Unlike other research studies  in this work  the framework proposed  is entirely based on unsupervised learning methods and so it is more  Fig. 5.A graph is drawn based on post pruning prescription medicines." />
    </node>
    <node TEXT="model">
      <node TEXT="Informatics in Medicine Unlocked 30  2022  100950 8likely to be used in real world applications as medical data are generally  unlabeled  and supervised learning models cannot be directly built using  these types of data. It is possible to recommend medicines by collecting a database of  patients   clinical symptoms resulting from clinical questionnaires  designed by the medical team  including personal information such as  age  height  weight  BMI   daily activity  patient history  underlying  diseases  and consumable medicines. Acknowledgement  We would like to thank  Behpardaz Jahan  Inc.  for helping us in  collecting the data." />
    </node>
  </node>
</map>
