<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="model">
      <node TEXT="Informatics in Medicine Unlocked 30  2022  100935 5 Fig. 3.The p value between different categories of lung involvement for all lobes together. The dashed black lines show the thresholds that we used in the  SVM model. Fig. 4.Significant differences between PDF of infection intensities for different lobes  top left  between two categories with infection degrees of 0 and 1  top right   between two categories with infection degrees of 1 and 2  bottom left  between two categories with infection degrees of 2 and 3  and bottom right  between two  categories with infection degrees of 3 and 4. Table 4  Minimum p values for each degree of infection compared with one level higher for five individual lobes and for all lobes together. p value Right Upper Lobe Right Middle Lobe Right Lower Lobe Left Upper Lobe Left Lower Lobe All Lobes  0 vs. 1 point 0.12 0.03 0.09 0.04 0.21 10 4  1 vs. 2 points 10 5 0.0001 0.0221 0.007 10 5 10 13  2 vs. 3 points 0.092 0.18 0.0003 0.054 0.005 10 8  3 vs. 4 points 0.185 0.105 0.021 0.094 0.095 0.008  4 vs. 5 points           0.093  M. Yousefzadeh et al." />
      <node TEXT="We collected 232 chest CT of  suspected patients and had them labeled by two radiologists in 6 classes  including a healthy class and 5 classes of  different infection severity. To segment the lung lobes  we used a pre trained U Net model with an average Dice  similarity coefficient  DSC  greater than 0.96. The introduced model can be used to generate a systematic automated report for  individual patients infected by COVID 19. 1.Introduction  SARS COV 2 infectious virus was identified by the World Health  Organization and now is recognized as COVID  19  1 2 . The current  gold standard of its diagnosis is the reverse transcription polymerase chain reaction  RT PCR  test  which is a specific molecular diagnosis  on respiratory specimens  throat swab nasopharyngeal swab   3 . Many  studies have reported a higher sensitivity for evaluations based on  computed tomography  CT  than RT PCR test  4 . Contents lists available at ScienceDirect  Informatics in Medicine Unlocked  u   zkw  s yo kr o     1ow  o to 1m y2w m k o2ty   https   doi.org 10.1016 j.imu.2022.100935  Received 23 February 2022  Received in revised form 28 March 2022  Accepted 29 March 2022" />
      <node TEXT="Hu  Yiqi  et al. showed that Chest CT findings  in patients who died of COVID 19 worsened with a moderate positive  correlation between CT severity and inflammatory factors associated  with leucocytes  neutrophils  and IL 2R  24 . In another work  Huang   Lu  et al.  25  showed that the quantification of lung opacification in  COVID 19 measured on Chest CT by using a commercially available  deep learning based tool was significantly different among groups with  different clinical severity. Bin Li et al.  26  presented a method for segmentation of  ground glass opacity  GGO  and juxta vascular nodules that showed  weak edges with inhomogeneous intensity characteristic. In a study  Kelei He and his colleagues pre  sented a multi task multi instance deep neural network  called M2  U Net  for assessment of COVID 19 by performing segmentation of the lung lobes. Using deep feature maps of chest CT images   Wajid Arshad Abbasi et al.  17  presented a COVID 19 severity predic   tion system for two different classes  severe vs. mild  called COVIDC   COVID 19 detection using CT scan . We observed that the pixel values  above  800 in normal lungs were associated with pulmonary arteries. Finally   using deep learning models directly on image data is also associated  with many challenges." />
      <node TEXT="In the pro  posed SVM model  we used a nonlinear radial basis function  RBF   kernel. In addition  to draw diagrams and results   the package  matplotlib   was used. By analyzing the PDF  we obtained a feature vector  for each lobe. Finally  by utilizing a SVM model  we predicted the  severity of infection in all five lung lobes. The DSC was calculated for 35 lung CT volumes with the lobes  labeled by a semi automatic method subsequently edited manually by a  radiologist  reported in Table 3 for each lobe . 4 suggests a significant difference between PDF of infection in  tensities for five lung lobes separately  demonstrating that our proposed  method can provide adequate differentiation between different config   urations of the infections per lobe. In most cases  the  confidence intervals for significant differences were more than 95 ." />
      <node TEXT="The results showed that  infection scores extracted from CT images are highly correlated with  laboratory findings and disease severity. COVID 19 related  infections appear on CT images of the chest with various patterns   including ground glass opacity  GGO   consolidation  crazy paving  etc. In summary  the main advantages and novelties of this study  are as follows     Internal dataset was collected and the severity of lung infection in six  classification classes was prepared. A U Net model with trained weight was used for lobe segmentation. Lung lobes segmentation  We used a pre trained model presented in Ref. CIP  Chest Imaging  Platform  is an open source lung segmentation tool based on threshold  and morphological operations. The Dice similarity coefficient  DSC  of  this network is reported 0.97  0.05 for standard approaches." />
      <node TEXT="Informatics in Medicine Unlocked 30  2022  100935 4classes  where their PDF assimilated the PDF of immediate different  levels of infection with a lower probability of separation. 4.Discussion  Due to a high prevalence of the recently epidemic COVID 19 and the  occurrence of infectious symptoms on the lung CT images  the use of  diagnostic tools based on deep machine learning approaches has an  important and prominent role in the field of diagnostic imaging  22 . In  this study  we used a deep learning model with U Net architecture to segment the lung lobes from the source  19   which showed a promising  result quite similar to manual labeling. Most statistical studies to evaluate the severity of infection seek to  find a link between CT findings and clinical and laboratory attributes   but due to small available populations  generalization of the results is  often limited. In a study in 2020  using  Pearson  s correlation test and  multivariate analysis curves have yielded a score of relationship be  tween patients   clinical findings  examining tests  and chest CT images. Promisingly  CT images were found capable to predict the mortality  from the disease  which could aid specifying the therapeutic approaches  Fig. 1.Lobe segmentation in three different views." />
    </node>
    <node TEXT="health">
      <node TEXT="We collected 232 chest CT of  suspected patients and had them labeled by two radiologists in 6 classes  including a healthy class and 5 classes of  different infection severity. To segment the lung lobes  we used a pre trained U Net model with an average Dice  similarity coefficient  DSC  greater than 0.96. The introduced model can be used to generate a systematic automated report for  individual patients infected by COVID 19. 1.Introduction  SARS COV 2 infectious virus was identified by the World Health  Organization and now is recognized as COVID  19  1 2 . The current  gold standard of its diagnosis is the reverse transcription polymerase chain reaction  RT PCR  test  which is a specific molecular diagnosis  on respiratory specimens  throat swab nasopharyngeal swab   3 . Many  studies have reported a higher sensitivity for evaluations based on  computed tomography  CT  than RT PCR test  4 . Contents lists available at ScienceDirect  Informatics in Medicine Unlocked  u   zkw  s yo kr o     1ow  o to 1m y2w m k o2ty   https   doi.org 10.1016 j.imu.2022.100935  Received 23 February 2022  Received in revised form 28 March 2022  Accepted 29 March 2022" />
    </node>
    <node TEXT="machine learning">
      <node TEXT="Informatics in Medicine Unlocked 30  2022  100935 4classes  where their PDF assimilated the PDF of immediate different  levels of infection with a lower probability of separation. 4.Discussion  Due to a high prevalence of the recently epidemic COVID 19 and the  occurrence of infectious symptoms on the lung CT images  the use of  diagnostic tools based on deep machine learning approaches has an  important and prominent role in the field of diagnostic imaging  22 . In  this study  we used a deep learning model with U Net architecture to segment the lung lobes from the source  19   which showed a promising  result quite similar to manual labeling. Most statistical studies to evaluate the severity of infection seek to  find a link between CT findings and clinical and laboratory attributes   but due to small available populations  generalization of the results is  often limited. In a study in 2020  using  Pearson  s correlation test and  multivariate analysis curves have yielded a score of relationship be  tween patients   clinical findings  examining tests  and chest CT images. Promisingly  CT images were found capable to predict the mortality  from the disease  which could aid specifying the therapeutic approaches  Fig. 1.Lobe segmentation in three different views." />
    </node>
  </node>
</map>
