<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="machine learning">
      <node TEXT="We  trained decision tree  random forest  support vector machine  SVM    logistic regression  and k nearest neighbor  KNN  classification algo  rithms to diagnose death or recovery data classes. Our random forest  model presented superior performance in predicting the outcome of  patients infected with novel coronavirus than previous approaches. In  42   the researchers used a combined method involving super   vised machine learning to identify an effective drug against coronavirus  infection." />
      <node TEXT="EMCNet  automated  COVID 19 diagnosis from X ray images using convolutional neural network and  ensemble of machine learning classifiers. 19  Silva Pedro  et al. COVID 19 detection in CT images with deep learning  a voting   based scheme and cross datasets analysis. 31  Santosh K. AI driven tools for coronavirus outbreak  need of active learning and  cross population train test models on multitudinal multimodal data." />
    </node>
    <node TEXT="model">
      <node TEXT="We  trained decision tree  random forest  support vector machine  SVM    logistic regression  and k nearest neighbor  KNN  classification algo  rithms to diagnose death or recovery data classes. Our random forest  model presented superior performance in predicting the outcome of  patients infected with novel coronavirus than previous approaches. In  42   the researchers used a combined method involving super   vised machine learning to identify an effective drug against coronavirus  infection." />
      <node TEXT="Naturally  the rules  indicate that intervals  1.5 2  are necessary for patients to recover  because they do not need artificial respiration. Random forest is an ensemble classification method based on the  majority vote and uses a combination of decision trees to classify data  classes. Although it has a higher computational complexity  past re  searches show that this classifier performs more beneficial than other  classification models due to its ensemble nature." />
      <node TEXT="Based on data provided in Table 4  it is obvious  that our model performs better in determining the outcome of corona   virus patients than the previous researches. 8.Grouped matrix diagram of extracted association rules with expected conditions  support 0.3  confidence 0.9  liftF1 . Table 3  Classification performance results to diagnosis the outcome of COVID 19 cases." />
      <node TEXT="EMCNet  automated  COVID 19 diagnosis from X ray images using convolutional neural network and  ensemble of machine learning classifiers. 19  Silva Pedro  et al. COVID 19 detection in CT images with deep learning  a voting   based scheme and cross datasets analysis. 31  Santosh K. AI driven tools for coronavirus outbreak  need of active learning and  cross population train test models on multitudinal multimodal data." />
      <node TEXT="Processing  In this stage  we train and test classification models using pre  processed data. In the literature  researchers have proposed many ma  chine learning approaches for different artificial intelligence  applications. Support  Indicates the percentage or number of D transactions that  include both X and Y." />
      <node TEXT="We implemented visualization  preprocessing  and classification  steps with the Python programming language version 3.5. 3.Result  In this section  we present the research results for different methods  separately. Confusion Matrix is a useful tool for examining the performance of  classification models in recognizing data class labels." />
    </node>
  </node>
</map>
