<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
  <node TEXT="topic">
    <node TEXT="health">
      <node TEXT="This is an open access article under the CC BY NC ND license   http   creativecommons.org licenses by  nc nd 4.0   .Virtual screening and molecular dynamics simulation study of plant  protease inhibitors against SARS CoV 2 envelope protein  Manisha Kirar  Hitesh Singh  Neelam Sehrawat   Department of Genetics  Maharshi Dayanand University  Rohtak  Haryana  India    ARTICLE INFO   Keywords   Plant protease inhibitors  Envelope protein  SARS CoV 2  Molecular docking  Molecular dynamics simulation etc ABSTRACT   Due to the outbreak of a new strain of pandemic coronavirus  there is a huge loss of economy and health. These plant   based protease inhibitors are a good target to fight against the new emerging strain of coronavirus because plant  extracted compounds are natural and there is fewer side effect than synthetic compounds. Around 2 million people lost their lives due to  no permanent cure for this dangerous virus  1 . Several types of research  are still going on all over the world to eliminate this disease. SARS CoV 2  Severe Acute Respiratory Syndrome  is a highly trans   missible human causative virus. The Pfizer BioNTech Comirnaty  vaccine was listed for WHO Emergency Use Listing  EUL  on 31  December 2020. Contents lists available at ScienceDirect  Informatics in Medicine Unlocked  u   zkw  s yo kr o     1ow  o to 1m y2w m k o2ty   https   doi.org 10.1016 j.imu.2022.100909  Received 7 January 2022  Received in revised form 6 March 2022  Accepted 6 March 2022" />
    </node>
    <node TEXT="model">
      <node TEXT="Informatics in Medicine Unlocked 30  2022  100909 5 Fig. 5.Molecular dynamics simulation of squash  kunitz and alpha amylase proteases inhibitors docked with E protein of SARS CO V. 3 D structure of interaction  a   b   deformability  c  d   B  factor  e  f   eigen value  g  h   variance map  I  j   correlation matrix  k  l   elastic network model  m  n . In the correlation matrix  Colored  bars showed the individual  red  and cumulative  green  variances. In the elastic network graph  dots are colored according to their stiffness  the darker greys  indicate stiffer springs and vice versa. For interpretation of the references to colour in this figure legend  the reader is referred to the Web version of this article. M. Kirar et al." />
      <node TEXT="Informatics in Medicine Unlocked 30  2022  100909 4evaluated for protein stability and motion of complex by molecular  dynamic simulation. iMODS facilitates the  exploration of such modes and generates feasible transition pathways  between two homologous structures  35 . TheiMOD server evaluates the  protein stability by computing its internal coordinates through normal  mode analysis  NMA . The stability of the protein is represented in terms of its main chain deformability plot  B factor values  eigen value   covariance matrix  and elastic network model. Structure analysis and visualization  Based on the binding affinity of protease inhibitors for SARS CoV 2  envelope protein  the complex structure was analyzed in Discovery  Fig. 4.Molecular docking and its binding pattern  in figure grey colour was used for ligand and red and green was used for envelope protein. In figures ligand alpha   amylase inhibitor wrightide r1  Fig." />
    </node>
  </node>
</map>
